import { supabase } from "./supabase";
import { getAcademicYearFromMonth } from "./financialData";

const INVOICE_BUCKET="cost-invoices";
async function currentUserId(){const{data:{user},error}=await supabase.auth.getUser();if(error)throw error;if(!user?.id)throw new Error("You must be signed in to manage invoices.");return user.id}
export async function uploadCostInvoiceDocument(file){if(!file)return null;const userId=await currentUserId();const allowed=["application/pdf","image/jpeg","image/png","image/webp"];if(!allowed.includes(file.type))throw new Error("Invoice documents must be PDF, JPG, PNG or WebP files.");if(file.size>10*1024*1024)throw new Error("Invoice documents must be 10 MB or smaller.");const safeName=(file.name||"invoice").replace(/[^a-zA-Z0-9._-]+/g,"-").replace(/-+/g,"-");const path=`transport/${userId}/${Date.now()}-${crypto.randomUUID()}-${safeName}`;const{error}=await supabase.storage.from(INVOICE_BUCKET).upload(path,file,{cacheControl:"3600",upsert:false,contentType:file.type});if(error)throw error;return path}
export async function getCostInvoiceDocumentUrl(path){if(!path)return null;if(/^https?:\/\//i.test(path))return path;const{data,error}=await supabase.storage.from(INVOICE_BUCKET).createSignedUrl(path,300);if(error)throw error;return data?.signedUrl||null}
export async function removeCostInvoiceDocument(path){if(!path||/^https?:\/\//i.test(path))return;const{error}=await supabase.storage.from(INVOICE_BUCKET).remove([path]);if(error)throw error}
export async function fetchCostInvoiceOptions(){const[schools,providers,categories]=await Promise.all([supabase.from("schools").select("id,code,name").eq("is_active",true).order("name"),supabase.from("providers").select("id,name,legal_name").order("name"),supabase.from("transport_cost_categories").select("id,code,name,cost_group,display_order").eq("is_active",true).order("display_order")]);if(schools.error)throw schools.error;if(providers.error)throw providers.error;if(categories.error)throw categories.error;return{schools:schools.data||[],providers:providers.data||[],categories:categories.data||[]}}
export async function fetchCostInvoices(costCentreCode="transport"){const{data,error}=await supabase.from("cost_invoices").select(`id,cost_centre_code,invoice_number,invoice_date,period_start,period_end,reporting_month,academic_year,scenario,status,posting_status,posted_at,subtotal,vat_amount,total_amount,reference,notes,attachment_url,provider:providers(id,name,legal_name),school:schools(id,code,name),lines:cost_invoice_lines(id,transport_cost_category_id,description,amount,category:transport_cost_categories(id,code,name,cost_group,display_order))`).eq("cost_centre_code",costCentreCode).eq("is_deleted",false).order("reporting_month",{ascending:false});if(error)throw error;return(data||[]).map(row=>({...row,providerId:row.provider?.id,providerName:row.provider?.name||"—",schoolId:row.school?.id,schoolCode:row.school?.code||"",schoolName:row.school?.name||row.school?.code||"—",invoiceNumber:row.invoice_number,invoiceDate:row.invoice_date,reportingMonth:row.reporting_month,academicYear:row.academic_year,postingStatus:row.posting_status||"Unposted",postedAt:row.posted_at,subtotal:Number(row.subtotal||0),vatAmount:Number(row.vat_amount||0),totalAmount:Number(row.total_amount||0),lines:(row.lines||[]).map(line=>({...line,categoryId:line.transport_cost_category_id,categoryName:line.category?.name||"Uncategorised",categoryCode:line.category?.code||"",costGroup:line.category?.cost_group||"other",amount:Number(line.amount||0)}))}))}
export async function saveCostInvoice(input){const userId=await currentUserId();if(input.id&&input.postingStatus==="Posted")throw new Error("Posted invoices cannot be edited. Unpost the invoice first if a correction is required.");if(!input.schoolId||!input.invoiceNumber||!input.reportingMonth)throw new Error("Complete school, invoice number and reporting month.");const lines=(input.lines||[]).filter(line=>line.categoryId&&Number(line.amount)!==0);if(!lines.length)throw new Error("Select a cost category and enter the invoice amount.");const subtotal=lines.reduce((sum,line)=>sum+Number(line.amount||0),0),vatAmount=Number(input.vatAmount||0),totalAmount=Number(input.totalAmount||subtotal+vatAmount),academicYear=getAcademicYearFromMonth(String(input.reportingMonth).slice(0,7));const header={cost_centre_code:input.costCentreCode||"transport",provider_id:input.providerId?Number(input.providerId):null,school_id:Number(input.schoolId),invoice_number:input.invoiceNumber.trim(),invoice_date:input.invoiceDate||null,period_start:input.periodStart||null,period_end:input.periodEnd||null,reporting_month:`${String(input.reportingMonth).slice(0,7)}-01`,academic_year:academicYear,scenario:input.scenario||"Actual",status:"Approved",subtotal,vat_amount:vatAmount,total_amount:totalAmount,reference:input.reference||null,notes:input.notes||null,attachment_url:input.attachmentUrl||null,updated_by:userId,updated_at:new Date().toISOString()};let invoiceId=input.id;if(invoiceId){const{error}=await supabase.from("cost_invoices").update(header).eq("id",invoiceId);if(error)throw error;const{error:deleteError}=await supabase.from("cost_invoice_lines").delete().eq("invoice_id",invoiceId);if(deleteError)throw deleteError}else{const{data,error}=await supabase.from("cost_invoices").insert({...header,created_by:userId}).select("id").single();if(error)throw error;invoiceId=data.id}const{error:lineError}=await supabase.from("cost_invoice_lines").insert(lines.map(line=>({invoice_id:invoiceId,transport_cost_category_id:Number(line.categoryId),description:line.description||null,amount:Number(line.amount||0)})));if(lineError)throw lineError;return{invoiceId,academicYear,subtotal,vatAmount,totalAmount}}
export async function getInvoicePostingConflicts(invoice){const categoryIds=[...new Set((invoice.lines||[]).map(line=>Number(line.categoryId)).filter(Boolean))];if(!categoryIds.length)return[];const month=String(invoice.reportingMonth).slice(0,10);const{data,error}=await supabase.from("transport_cost_records").select("id,category_id,amount,category:transport_cost_categories(id,name)").eq("school_id",Number(invoice.schoolId)).eq("month",month).eq("scenario",invoice.scenario||"Actual").eq("source_type","monthly_total").eq("is_deleted",false).in("category_id",categoryIds);if(error)throw error;return(data||[]).map(row=>({id:row.id,categoryId:row.category_id,categoryName:row.category?.name||"Cost category",amount:Number(row.amount||0)}))}
export async function postCostInvoice(invoice){if(invoice.postingStatus==="Posted")return;await currentUserId();const{error}=await supabase.rpc("post_transport_cost_invoice",{p_invoice_id:invoice.id});if(error)throw error}
export async function unpostCostInvoice(invoice){if(invoice.postingStatus!=="Posted")return;await currentUserId();const{error}=await supabase.rpc("unpost_transport_cost_invoice",{p_invoice_id:invoice.id});if(error)throw error}
