import { supabase } from "./supabase";

const SCHOOL_DISPLAY = { FRY:"Fry", ROSE:"Rose", RDXB:"Repton Dubai", RAB:"Repton Al Barsha" };
const LEGACY_PROVIDER_ALIASES = {"Gulf Star / Evolve":"Evolve Academy (Budo Juku Sports Consultancy LLC)","Chinese Language Institute":"Chinese Language Institute Middle East (CLIME)","Alliance Francaise":"Alliance Française Abu Dhabi","Badminton Academy":"Day Light Sports Academy L.L.C - O.P.","Basketball Academy":"RnB Sports Managemen","Peak Sports":"Peak Sports Academy – LLC","Gulf Multi Sport":"Gulf Multi Sports","Proactive Soccer School":"Proactive Soccer School LTD","Champs Gymnastics":"Champs Gymnastics Academy","Prototype Fitness":"Prototype Fitness Sports Academy","Neptune Swimming Club":"Neptune Swimming Academy","Global Sports RS":"Global Sports Recreation Services LLC"};
function normaliseProviderName(value){return String(value||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[–—]/g,"-").replace(/\s+/g," ").trim().toLowerCase();}
function createFallbackProvider(providerName){const cleanName=String(providerName||"").trim();return{id:null,name:cleanName,contactPerson:"",email:"",phone:"",companyNumber:"",address:"",programmes:[],contract:{status:"Not Recorded",startDate:"",expiryDate:"",noticePeriod:"",commissionRate:null,rentalFees:null,revenueCollection:"",invoiceFrequency:"",schools:[]}};}
function mapContract(contract){if(!contract)return null;const rentalFees=contract.rental_fees_description||(contract.rental_fees_amount==null?null:Number(contract.rental_fees_amount));return{id:contract.id,status:contract.status||"Not Recorded",startDate:contract.start_date||"",expiryDate:contract.expiry_date||"",noticePeriod:contract.notice_period||"",commissionRate:contract.commission_rate==null?null:Number(contract.commission_rate),rentalFees,revenueCollection:contract.revenue_collection||"",invoiceFrequency:contract.invoice_frequency||"",schools:(contract.provider_contract_schools||[]).map(item=>item.school?.code).filter(Boolean).map(code=>SCHOOL_DISPLAY[code]||code)};}
function chooseCurrentContract(contracts=[]){if(!Array.isArray(contracts)||contracts.length===0)return null;const leasing=contracts.filter(c=>c.revenue_stream?.code==="leasing");const candidates=leasing.length?leasing:contracts;return[...candidates].sort((a,b)=>{if(Boolean(a.is_active)!==Boolean(b.is_active))return a.is_active?-1:1;const aDate=a.expiry_date||a.start_date||"",bDate=b.expiry_date||b.start_date||"";return String(bDate).localeCompare(String(aDate));})[0];}
function mapProvider(row){const contract=chooseCurrentContract(row.provider_contracts||[]);const contacts=(row.supplier_contacts||[]).filter(c=>c.is_active!==false).sort((a,b)=>Number(Boolean(b.is_primary))-Number(Boolean(a.is_primary)));const primary=contacts.find(c=>c.is_primary)||contacts[0]||null;return{id:row.id,name:row.name||"",contactPerson:primary?.contact_name||row.contact_person||"",email:primary?.email||row.email||"",phone:primary?.phone||row.phone||"",companyNumber:row.company_number||"",address:row.address||"",programmes:(row.programmes||[]).map(p=>p.name).filter(Boolean).sort((a,b)=>a.localeCompare(b)),contract:mapContract(contract)||createFallbackProvider(row.name).contract};}
let providerCache=[],providerLoadPromise=null;
export async function fetchProviders({force=false}={}){if(!force&&providerCache.length)return providerCache;if(!force&&providerLoadPromise)return providerLoadPromise;providerLoadPromise=(async()=>{const{data,error}=await supabase.from("providers").select(`id,name,contact_person,email,phone,company_number,address,programmes(id,name),supplier_contacts(id,contact_name,role,email,phone,is_primary,is_active),provider_contracts(id,status,start_date,expiry_date,notice_period,commission_rate,rental_fees_amount,rental_fees_description,revenue_collection,invoice_frequency,is_active,revenue_stream:revenue_streams(code),provider_contract_schools(school:schools(id,code,name)))`).eq("is_active",true).order("name",{ascending:true});if(error)throw error;providerCache=(data||[]).map(mapProvider);return providerCache;})();try{return await providerLoadPromise;}finally{providerLoadPromise=null;}}
export function getProviderByName(providerName,providers=providerCache){const cleanName=String(providerName||"").trim();if(!cleanName)return null;const aliasTarget=LEGACY_PROVIDER_ALIASES[cleanName]||cleanName,requested=normaliseProviderName(aliasTarget);return(providers||[]).find(item=>normaliseProviderName(item.name)===requested)||createFallbackProvider(cleanName);}
export function getAllProviders(){return providerCache;}
export function clearProviderCache(){providerCache=[];providerLoadPromise=null;}
fetchProviders().catch(error=>console.error("Unable to preload providers from Supabase:",error));
export default providerCache;
