import { supabase } from "./supabase";
const SCHOOL_DISPLAY={FRY:"Fry",ROSE:"Rose",RDXB:"Repton Dubai",RAB:"Repton Al Barsha"};
function createFallbackProvider(providerName=""){const cleanName=String(providerName||"").trim();return{id:null,name:cleanName,contactPerson:"",email:"",phone:"",companyNumber:"",address:"",programmes:[],contract:{status:"Not Recorded",startDate:"",expiryDate:"",noticePeriod:"",commissionRate:null,rentalFees:null,revenueCollection:"",invoiceFrequency:"",schools:[]}}}
function mapContract(contract){if(!contract)return null;const rentalFees=contract.rental_fees_description||(contract.rental_fees_amount==null?null:Number(contract.rental_fees_amount));return{id:contract.id,status:contract.status||"Not Recorded",startDate:contract.start_date||"",expiryDate:contract.expiry_date||"",noticePeriod:contract.notice_period||"",commissionRate:contract.commission_rate==null?null:Number(contract.commission_rate),rentalFees,revenueCollection:contract.revenue_collection||"",invoiceFrequency:contract.invoice_frequency||"",schools:(contract.provider_contract_schools||[]).map(item=>item.school?.code).filter(Boolean).map(code=>SCHOOL_DISPLAY[code]||code)}}
function chooseCurrentContract(contracts=[]){if(!Array.isArray(contracts)||!contracts.length)return null;const leasing=contracts.filter(c=>c.revenue_stream?.code==="leasing"),candidates=leasing.length?leasing:contracts;return[...candidates].sort((a,b)=>{if(Boolean(a.is_active)!==Boolean(b.is_active))return a.is_active?-1:1;return String(b.expiry_date||b.start_date||"").localeCompare(String(a.expiry_date||a.start_date||""))})[0]}
function mapProvider(row){const contract=chooseCurrentContract(row.provider_contracts||[]),contacts=(row.supplier_contacts||[]).filter(c=>c.is_active!==false).sort((a,b)=>Number(Boolean(b.is_primary))-Number(Boolean(a.is_primary))),primary=contacts.find(c=>c.is_primary)||contacts[0]||null;return{id:row.id,name:row.name||"",contactPerson:primary?.contact_name||row.contact_person||"",email:primary?.email||row.email||"",phone:primary?.phone||row.phone||"",companyNumber:row.company_number||"",address:row.address||"",programmes:(row.programmes||[]).map(p=>p.name).filter(Boolean).sort((a,b)=>a.localeCompare(b)),contract:mapContract(contract)||createFallbackProvider(row.name).contract}}
let providerCache=[],providerLoadPromise=null;
export async function fetchProviders({force=false}={}){if(!force&&providerCache.length)return providerCache;if(!force&&providerLoadPromise)return providerLoadPromise;providerLoadPromise=(async()=>{const{data,error}=await supabase.from("providers").select(`id,name,contact_person,email,phone,company_number,address,programmes(id,name),supplier_contacts(id,contact_name,role,email,phone,is_primary,is_active),provider_contracts(id,status,start_date,expiry_date,notice_period,commission_rate,rental_fees_amount,rental_fees_description,revenue_collection,invoice_frequency,is_active,revenue_stream:revenue_streams(code),provider_contract_schools(school:schools(id,code,name)))`).eq("is_active",true).order("name",{ascending:true});if(error)throw error;providerCache=(data||[]).map(mapProvider);return providerCache})();try{return await providerLoadPromise}finally{providerLoadPromise=null}}
export function getProviderById(providerId,providers=providerCache){if(providerId===null||providerId===undefined||providerId==="")return null;return(providers||[]).find(item=>String(item.id)===String(providerId))||null}
export function getAllProviders(){return providerCache}
export function clearProviderCache(){providerCache=[];providerLoadPromise=null}
fetchProviders().catch(error=>console.error("Unable to preload providers from Supabase:",error));
export default providerCache;
