-- Contracted / expected revenue context for revenue streams such as Kitchen Rental and Enrich ME.
-- This is deliberately separate from financial_records: targets describe the commercial expectation;
-- financial_records remain the source of truth for monthly Actual/Budget/Forecast reporting.

begin;

create table if not exists public.revenue_contract_targets (
  id bigint generated by default as identity primary key,
  school_id bigint not null references public.schools(id) on delete cascade,
  revenue_stream_id bigint not null references public.revenue_streams(id) on delete cascade,
  programme_id bigint null references public.programmes(id) on delete cascade,
  academic_year text not null,
  contracted_amount numeric(14,2) not null check (contracted_amount >= 0),
  allocation_method text not null default 'no_monthly_allocation'
    check (allocation_method in ('no_monthly_allocation','even_monthly','custom')),
  notes text null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists revenue_contract_targets_unique_idx
  on public.revenue_contract_targets (
    school_id,
    revenue_stream_id,
    coalesce(programme_id, 0),
    academic_year
  )
  where is_active = true;

alter table public.revenue_contract_targets enable row level security;

drop policy if exists "Authenticated users can read revenue contract targets" on public.revenue_contract_targets;
create policy "Authenticated users can read revenue contract targets"
  on public.revenue_contract_targets for select
  to authenticated
  using (true);

-- Seed the existing Kitchen Rental commercial expectation without creating future Actual months.
insert into public.revenue_contract_targets (
  school_id, revenue_stream_id, programme_id, academic_year, contracted_amount, allocation_method, notes
)
select s.id, rs.id, null, 'AY2026-27', 400000, 'even_monthly', 'Annual contractual Kitchen Rental value'
from public.schools s
join public.revenue_streams rs on rs.code = 'kitchen_rental'
where s.code = 'RDXB'
  and not exists (
    select 1 from public.revenue_contract_targets t
    where t.school_id = s.id
      and t.revenue_stream_id = rs.id
      and t.programme_id is null
      and t.academic_year = 'AY2026-27'
      and t.is_active = true
  );

commit;
