-- Generic Cost Invoice Register
-- Invoice headers and line allocations for operational cost centres.
-- Transport is the first consumer; the structure can support future cost centres.
-- Run in Supabase SQL Editor before using the Invoice Register UI. Safe to rerun.

begin;

create table if not exists public.cost_invoices (
  id bigint generated by default as identity primary key,
  cost_centre_code text not null,
  provider_id bigint references public.providers(id) on delete restrict,
  school_id bigint not null references public.schools(id) on delete restrict,
  invoice_number text not null,
  invoice_date date not null,
  period_start date,
  period_end date,
  reporting_month date not null,
  academic_year text not null,
  scenario text not null default 'Actual',
  status text not null default 'Received' check (status in ('Received','Under Review','Approved','Paid','Disputed','Cancelled')),
  subtotal numeric(14,2) not null default 0,
  vat_amount numeric(14,2) not null default 0,
  total_amount numeric(14,2) not null default 0,
  reference text,
  notes text,
  attachment_url text,
  is_deleted boolean not null default false,
  created_by uuid,
  updated_by uuid,
  deleted_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create table if not exists public.cost_invoice_lines (
  id bigint generated by default as identity primary key,
  invoice_id bigint not null references public.cost_invoices(id) on delete cascade,
  transport_cost_category_id bigint references public.transport_cost_categories(id) on delete restrict,
  description text,
  amount numeric(14,2) not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create unique index if not exists cost_invoices_unique_active_number_idx
  on public.cost_invoices (cost_centre_code, provider_id, invoice_number)
  where is_deleted = false;
create index if not exists cost_invoices_school_idx on public.cost_invoices(school_id);
create index if not exists cost_invoices_reporting_month_idx on public.cost_invoices(reporting_month);
create index if not exists cost_invoice_lines_invoice_idx on public.cost_invoice_lines(invoice_id);

alter table public.cost_invoices enable row level security;
alter table public.cost_invoice_lines enable row level security;

drop policy if exists "Authenticated users can read cost invoices" on public.cost_invoices;
create policy "Authenticated users can read cost invoices" on public.cost_invoices for select to authenticated using (true);
drop policy if exists "Authenticated users can insert cost invoices" on public.cost_invoices;
create policy "Authenticated users can insert cost invoices" on public.cost_invoices for insert to authenticated with check (true);
drop policy if exists "Authenticated users can update cost invoices" on public.cost_invoices;
create policy "Authenticated users can update cost invoices" on public.cost_invoices for update to authenticated using (true) with check (true);

drop policy if exists "Authenticated users can read cost invoice lines" on public.cost_invoice_lines;
create policy "Authenticated users can read cost invoice lines" on public.cost_invoice_lines for select to authenticated using (true);
drop policy if exists "Authenticated users can insert cost invoice lines" on public.cost_invoice_lines;
create policy "Authenticated users can insert cost invoice lines" on public.cost_invoice_lines for insert to authenticated with check (true);
drop policy if exists "Authenticated users can update cost invoice lines" on public.cost_invoice_lines;
create policy "Authenticated users can update cost invoice lines" on public.cost_invoice_lines for update to authenticated using (true) with check (true);
drop policy if exists "Authenticated users can delete cost invoice lines" on public.cost_invoice_lines;
create policy "Authenticated users can delete cost invoice lines" on public.cost_invoice_lines for delete to authenticated using (true);

grant select,insert,update on public.cost_invoices to authenticated;
grant select,insert,update,delete on public.cost_invoice_lines to authenticated;
grant usage,select on all sequences in schema public to authenticated;

commit;
