-- Provider / contract schema for Commercial Operations Dashboard
-- Version-controlled database definition only. Provider contact/data rows are not committed.

begin;

alter table public.providers
  add column if not exists company_number text,
  add column if not exists address text,
  add column if not exists updated_at timestamptz not null default now();

create table if not exists public.provider_contracts (
  id bigint generated by default as identity primary key,
  provider_id bigint not null references public.providers(id) on delete cascade,
  status text not null default 'Not Recorded',
  start_date date,
  expiry_date date,
  notice_period text,
  commission_rate numeric,
  rental_fees_amount numeric,
  rental_fees_description text,
  revenue_collection text,
  invoice_frequency text,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_provider_contracts_provider_id
  on public.provider_contracts(provider_id);
create index if not exists idx_provider_contracts_expiry_date
  on public.provider_contracts(expiry_date);
create index if not exists idx_provider_contracts_is_active
  on public.provider_contracts(is_active);

create table if not exists public.provider_contract_schools (
  provider_contract_id bigint not null
    references public.provider_contracts(id) on delete cascade,
  school_id bigint not null
    references public.schools(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (provider_contract_id, school_id)
);

create index if not exists idx_provider_contract_schools_school_id
  on public.provider_contract_schools(school_id);

alter table public.provider_contracts enable row level security;
alter table public.provider_contract_schools enable row level security;

drop policy if exists "Authenticated users can read provider contracts"
  on public.provider_contracts;
create policy "Authenticated users can read provider contracts"
  on public.provider_contracts
  for select
  to authenticated
  using (true);

drop policy if exists "Authenticated users can read provider contract schools"
  on public.provider_contract_schools;
create policy "Authenticated users can read provider contract schools"
  on public.provider_contract_schools
  for select
  to authenticated
  using (true);

grant select on public.provider_contracts to authenticated;
grant select on public.provider_contract_schools to authenticated;

commit;
