-- Supplier & Contract Register schema extension
-- Keeps Leasing programme/provider usage intact while allowing cross-stream contracts.
-- Safe to rerun: additions are idempotent and unknown commercial terms may remain null.

begin;

-- Supplier/company identity. Existing providers.name remains the display name used by Leasing.
alter table public.providers
  add column if not exists legal_name text,
  add column if not exists vat_trn text;

-- Each contract carries the revenue-stream relationship, not the supplier itself.
alter table public.provider_contracts
  add column if not exists revenue_stream_id bigint
    references public.revenue_streams(id) on delete restrict;

create index if not exists idx_provider_contracts_revenue_stream_id
  on public.provider_contracts(revenue_stream_id);

-- Multiple contacts per supplier. The legacy contact_person/email/phone columns on
-- providers remain supported and can continue serving the Leasing provider details.
create table if not exists public.supplier_contacts (
  id bigint generated by default as identity primary key,
  provider_id bigint not null references public.providers(id) on delete cascade,
  contact_name text not null,
  role text,
  email text,
  phone text,
  is_primary boolean not null default false,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_supplier_contacts_provider_id
  on public.supplier_contacts(provider_id);
create index if not exists idx_supplier_contacts_is_active
  on public.supplier_contacts(is_active);

alter table public.supplier_contacts enable row level security;

drop policy if exists "Authenticated users can read supplier contacts"
  on public.supplier_contacts;
create policy "Authenticated users can read supplier contacts"
  on public.supplier_contacts
  for select
  to authenticated
  using (true);

grant select on public.supplier_contacts to authenticated;

-- Existing provider contracts were created from the Leasing provider directory.
-- Backfill only rows that do not already have a stream assigned.
update public.provider_contracts pc
set revenue_stream_id = rs.id
from public.revenue_streams rs
where rs.code = 'leasing'
  and pc.revenue_stream_id is null;

-- Readable register view. One row represents one contract relationship.
-- Schools and contacts are returned as JSON arrays so the UI can show all known details.
create or replace view public.supplier_contract_register as
select
  pc.id as contract_id,
  p.id as provider_id,
  p.name as supplier_name,
  p.legal_name,
  p.contact_person,
  p.email,
  p.phone,
  p.company_number,
  p.vat_trn,
  p.address,
  rs.id as revenue_stream_id,
  rs.code as revenue_stream_code,
  rs.name as revenue_stream_name,
  pc.status,
  pc.start_date,
  pc.expiry_date,
  pc.notice_period,
  pc.commission_rate,
  pc.rental_fees_amount,
  pc.rental_fees_description,
  pc.revenue_collection,
  pc.invoice_frequency,
  pc.is_active,
  coalesce(school_data.schools, '[]'::jsonb) as schools,
  coalesce(contact_data.contacts, '[]'::jsonb) as contacts
from public.provider_contracts pc
join public.providers p on p.id = pc.provider_id
left join public.revenue_streams rs on rs.id = pc.revenue_stream_id
left join lateral (
  select jsonb_agg(
    jsonb_build_object(
      'id', s.id,
      'code', s.code,
      'name', s.name
    ) order by s.name
  ) as schools
  from public.provider_contract_schools pcs
  join public.schools s on s.id = pcs.school_id
  where pcs.provider_contract_id = pc.id
) school_data on true
left join lateral (
  select jsonb_agg(
    jsonb_build_object(
      'id', sc.id,
      'name', sc.contact_name,
      'role', sc.role,
      'email', sc.email,
      'phone', sc.phone,
      'isPrimary', sc.is_primary
    ) order by sc.is_primary desc, sc.contact_name
  ) as contacts
  from public.supplier_contacts sc
  where sc.provider_id = p.id
    and sc.is_active = true
) contact_data on true;

grant select on public.supplier_contract_register to authenticated;

commit;
