-- Transport Cost Centre — Phase 1
-- Monthly cost ledger by school, month and cost category.
-- Detailed trip/invoice records can be layered on later without changing this structure.
-- Safe to rerun.

begin;

create table if not exists public.transport_cost_categories (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  cost_group text not null check (cost_group in ('trips', 'contractual', 'other', 'offset')),
  display_order integer not null default 0,
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.transport_cost_records (
  id bigint generated by default as identity primary key,
  school_id bigint not null references public.schools(id),
  category_id bigint not null references public.transport_cost_categories(id),
  academic_year text not null,
  month date not null,
  scenario text not null default 'Actual',
  amount numeric(14,2) not null default 0,
  notes text,
  source_type text not null default 'monthly_total',
  is_deleted boolean not null default false,
  created_by uuid,
  updated_by uuid,
  deleted_by uuid,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);

create unique index if not exists transport_cost_records_unique_entry_idx
  on public.transport_cost_records (school_id, category_id, month, scenario)
  where is_deleted = false;

create index if not exists transport_cost_records_month_idx
  on public.transport_cost_records (month);

create index if not exists transport_cost_records_school_idx
  on public.transport_cost_records (school_id);

insert into public.transport_cost_categories (code, name, cost_group, display_order)
values
  ('day_trips', 'Day Trips', 'trips', 10),
  ('sports_trips', 'Sports Trips', 'trips', 20),
  ('boarding_trips', 'Boarding Trips', 'trips', 30),
  ('other_trips', 'Other Trips', 'trips', 40),
  ('supplemental_fee', 'Contract Expenses - Supplemental Fee', 'contractual', 50),
  ('bus_guardian_fees', 'Contract Expenses - Bus Guardian Fees', 'contractual', 60),
  ('staff_transport', 'Staff Transport', 'contractual', 70),
  ('minimum_capacity_shortfall', 'Minimum Capacity Utilisation Shortfall', 'contractual', 80),
  ('excess_charges', 'Excess Charges', 'other', 90),
  ('other_charges', 'Other Charges', 'other', 100),
  ('subsidy_credit', 'Subsidy / Credit', 'offset', 110)
on conflict (code) do update set
  name = excluded.name,
  cost_group = excluded.cost_group,
  display_order = excluded.display_order,
  is_active = true;

alter table public.transport_cost_categories enable row level security;
alter table public.transport_cost_records enable row level security;

drop policy if exists "Authenticated users can read transport cost categories" on public.transport_cost_categories;
create policy "Authenticated users can read transport cost categories"
  on public.transport_cost_categories for select to authenticated using (true);

drop policy if exists "Authenticated users can read transport cost records" on public.transport_cost_records;
create policy "Authenticated users can read transport cost records"
  on public.transport_cost_records for select to authenticated using (true);

drop policy if exists "Authenticated users can insert transport cost records" on public.transport_cost_records;
create policy "Authenticated users can insert transport cost records"
  on public.transport_cost_records for insert to authenticated with check (true);

drop policy if exists "Authenticated users can update transport cost records" on public.transport_cost_records;
create policy "Authenticated users can update transport cost records"
  on public.transport_cost_records for update to authenticated using (true) with check (true);

grant select on public.transport_cost_categories to authenticated;
grant select, insert, update on public.transport_cost_records to authenticated;
grant usage, select on all sequences in schema public to authenticated;

commit;
