import { useEffect, useMemo, useRef, useState } from "react";
import { useOutletContext } from "react-router-dom";
import DashboardCurrencyTooltip from "../../components/dashboard/DashboardCurrencyTooltip";
import KpiCard from "../../components/dashboard/KpiCard";
import ManageRecordsLink from "../../components/dashboard/ManageRecordsLink";
import MonthlyResultsTable from "../../components/dashboard/MonthlyResultsTable";
import MonthlyTrendChart from "../../components/dashboard/MonthlyTrendChart";
import PerformanceChart from "../../components/dashboard/PerformanceChart";
import "../../components/dashboard/dashboardComponents.css";
import { fetchUniformRecords,filterUniformRecords,formatCompactCurrency,formatCurrency,formatPercentage,getUniformAcademicYears,getUniformSchools,getUniformSummary,getMonthlyUniformData,getSchoolUniformData,getTermUniformData } from "../../lib/uniformData";
import "./UniformDashboardPage.css";
export default function UniformDashboardPage(){
 const {setHeaderControls}=useOutletContext(),[records,setRecords]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[yearBasis,setYearBasis]=useState("finance"),[filters,setFilters]=useState({academicYear:"",school:""}),hasInitialisedAcademicYear=useRef(false);
 useEffect(()=>{let active=true;(async()=>{try{setLoading(true);setError("");const data=await fetchUniformRecords();if(active)setRecords(data)}catch(loadError){console.error("Unable to load Uniform records",loadError);if(active)setError(loadError?.message||"Unable to load Uniform data from Supabase.")}finally{if(active)setLoading(false)}})();return()=>{active=false}},[]);
 const uniformAcademicYears=useMemo(()=>getUniformAcademicYears(records,yearBasis),[records,yearBasis]),uniformSchools=useMemo(()=>getUniformSchools(records),[records]),latestAcademicYear=uniformAcademicYears[uniformAcademicYears.length-1]||"";
 useEffect(()=>{if(!hasInitialisedAcademicYear.current&&latestAcademicYear){setFilters(c=>({...c,academicYear:latestAcademicYear}));hasInitialisedAcademicYear.current=true}},[latestAcademicYear]);
 useEffect(()=>{if(filters.academicYear&&!uniformAcademicYears.includes(filters.academicYear))setFilters(c=>({...c,academicYear:latestAcademicYear}))},[yearBasis,uniformAcademicYears,latestAcademicYear,filters.academicYear]);
 const filteredRecords=useMemo(()=>filterUniformRecords(records,{...filters,yearBasis}),[records,filters,yearBasis]),summary=useMemo(()=>getUniformSummary(filteredRecords),[filteredRecords]),monthlyData=useMemo(()=>getMonthlyUniformData(filteredRecords,yearBasis),[filteredRecords,yearBasis]),schoolData=useMemo(()=>getSchoolUniformData(filteredRecords),[filteredRecords]),termData=useMemo(()=>getTermUniformData(filteredRecords),[filteredRecords]),tableResetKey=`${filters.academicYear}|${filters.school}|${yearBasis}`;
 function handleFilterChange(name,value){setFilters(c=>({...c,[name]:value}))}
 useEffect(()=>{setHeaderControls(<div className="header-page-filters"><label className="header-filter-control"><span>Academic Year</span><select value={filters.academicYear} onChange={e=>handleFilterChange("academicYear",e.target.value)}><option value="">All Years</option>{uniformAcademicYears.map(year=><option key={year} value={year}>{year}</option>)}</select></label><label className="header-filter-control wide"><span>School</span><select value={filters.school} onChange={e=>handleFilterChange("school",e.target.value)}><option value="">All Schools</option>{uniformSchools.map(s=><option key={s.code} value={s.code}>{s.name}</option>)}</select></label><div className="uniform-year-basis-control"><span>Uniform Year Basis</span><div className="uniform-year-basis-toggle" aria-label="Academic year basis"><button type="button" className={yearBasis==="finance"?"active":""} onClick={()=>setYearBasis("finance")} title="Finance reporting: September to August">Sep–Aug</button><button type="button" className={yearBasis==="backToSchool"?"active":""} onClick={()=>setYearBasis("backToSchool")} title="Back-to-school view: August to July">Aug–Jul</button></div></div></div>);return()=>setHeaderControls(null)},[filters,yearBasis,uniformAcademicYears,uniformSchools,setHeaderControls]);
 if(loading)return <section className="dashboard-page uniform-dashboard-page"><div className="dashboard-loading-state">Loading Uniform data…</div></section>;if(error)return <section className="dashboard-page uniform-dashboard-page"><div className="dashboard-error-state">Unable to load Uniform data: {error}</div></section>;
 const currencyTooltip=<DashboardCurrencyTooltip formatValue={formatCurrency}/>,monthlyColumns=[{key:"academicYear",label:"Academic Year"},{key:"label",label:"Month"},{key:"term",label:"Term"},{key:"sales",label:"Sales",numeric:true,tone:"sales",render:formatCurrency},{key:"commission",label:"Commission",numeric:true,tone:"commission",render:formatCurrency},{key:"commissionRate",label:"Commission Rate",numeric:true,render:formatPercentage}],termDescription=yearBasis==="finance"?"Performance across finance terms.":"Performance across back-to-school terms.";
 return <section className="dashboard-page uniform-dashboard-page"><section className="dashboard-kpi-grid"><KpiCard label="Total Sales" value={formatCurrency(summary.sales)} detail={`${summary.months} reporting months`}/><KpiCard label="Total Commission" value={formatCurrency(summary.commission)} detail={`${summary.schools} schools included`}/><KpiCard label="Effective Commission Rate" value={formatPercentage(summary.commissionRate)} detail="Commission divided by uniform sales"/><KpiCard label="Average Monthly Sales" value={formatCurrency(summary.averageMonthlySales)} detail="Average across the selected period"/></section><section className="dashboard-two-column-grid"><PerformanceChart title="School Performance" description="Sales and commission by school." data={schoolData} categoryKey="school" formatAxis={formatCompactCurrency} formatValue={formatCurrency} tooltipContent={currencyTooltip} defaultMetric="Overview" defaultView="Bar"/><PerformanceChart title="Term Performance" description={termDescription} data={termData} categoryKey="term" formatAxis={formatCompactCurrency} formatValue={formatCurrency} tooltipContent={currencyTooltip} defaultMetric="Sales" defaultView="Pie"/></section><MonthlyTrendChart data={monthlyData} formatAxis={formatCompactCurrency} tooltipContent={currencyTooltip} className="dashboard-wide-card"/><MonthlyResultsTable data={monthlyData} columns={monthlyColumns} totals={{sales:formatCurrency(summary.sales),commission:formatCurrency(summary.commission),commissionRate:formatPercentage(summary.commissionRate)}} emptyMessage="No uniform records match the selected filters." resetKey={tableResetKey}/><ManageRecordsLink label="Manage Uniform Records" to="/financial-records?area=monthly-reporting&stream=uniform&view=register"/></section>
}
