import { useEffect, useMemo, useState } from "react";
import { Link, useOutletContext } from "react-router-dom";
import {
  Bar,
  BarChart,
  CartesianGrid,
  Cell,
  Legend,
  Line,
  LineChart,
  Pie,
  PieChart,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from "recharts";

import leasingSource from "../../data/leasing-data.json";
import cateringSource from "../../data/catering-data.json";
import uniformSource from "../../data/uniform-data.json";
import providerSource from "../../data/provider-data.json";

import "./DashboardPage.css";

const STREAM_COLOURS = { Leasing: "#6d5dfc", Catering: "#159f8c", Uniform: "#e97832" };
const SCHOOL_NAMES = { RDXB: "Repton Dubai", RAB: "Repton Al Barsha", FRY: "Repton Fry", ROSE: "Repton Rose", Fry: "Repton Fry", Rose: "Repton Rose" };
const MONTH_ORDER = [9,10,11,12,1,2,3,4,5,6,7,8];
function unique(values){return [...new Set(values.filter(Boolean))]}
function toNumber(value){const number=Number(value);return Number.isFinite(number)?number:0}
function formatCurrency(value){return new Intl.NumberFormat("en-AE",{style:"currency",currency:"AED",maximumFractionDigits:0}).format(toNumber(value))}
function formatCompactCurrency(value){return new Intl.NumberFormat("en-AE",{style:"currency",currency:"AED",notation:"compact",maximumFractionDigits:1}).format(toNumber(value))}
function formatPercent(value){return Number.isFinite(value)?`${value.toFixed(1)}%`:"—"}
function getLatestAcademicYear(years){return [...years].sort((a,b)=>b.localeCompare(a))[0]||""}
function getSchoolLabel(value){return SCHOOL_NAMES[value]||value||"Unknown"}
function getLeasingSummary(records){let sales=0,commission=0,rentalFees=0;records.forEach(record=>{const amount=toNumber(record.amount);if(record.incomeType==="Sales")sales+=amount;if(record.incomeType==="Commission")commission+=amount;if(record.incomeType==="Rental Fees")rentalFees+=amount});return {revenue:sales+rentalFees,income:commission+rentalFees}}
function getSalesCommissionSummary(records){let sales=0,commission=0;records.forEach(record=>{const amount=toNumber(record.amount);if(record.metric==="Sales")sales+=amount;if(record.metric==="Commission")commission+=amount});return {revenue:sales,income:commission}}
function buildSchoolData({leasingRecords,cateringRecords,uniformRecords}){const grouped=new Map();function getEntry(school){const schoolName=getSchoolLabel(school);if(!grouped.has(schoolName))grouped.set(schoolName,{school:schoolName,revenue:0,income:0});return grouped.get(schoolName)}leasingRecords.forEach(record=>{const entry=getEntry(record.school),amount=toNumber(record.amount);if(record.incomeType==="Sales")entry.revenue+=amount;if(record.incomeType==="Commission")entry.income+=amount;if(record.incomeType==="Rental Fees"){entry.revenue+=amount;entry.income+=amount}});[...cateringRecords,...uniformRecords].forEach(record=>{const entry=getEntry(record.schoolName||record.school),amount=toNumber(record.amount);if(record.metric==="Sales")entry.revenue+=amount;if(record.metric==="Commission")entry.income+=amount});return [...grouped.values()].sort((a,b)=>b.revenue-a.revenue)}
function buildMonthlyTrend({leasingRecords,cateringRecords,uniformRecords}){const grouped=new Map();function getEntry(monthKey){if(!grouped.has(monthKey))grouped.set(monthKey,{month:monthKey,revenue:0,income:0});return grouped.get(monthKey)}leasingRecords.forEach(record=>{const monthKey=record.termStart?String(record.termStart).slice(0,7):"";if(!monthKey)return;const entry=getEntry(monthKey),amount=toNumber(record.amount);if(record.incomeType==="Sales")entry.revenue+=amount;if(record.incomeType==="Commission")entry.income+=amount;if(record.incomeType==="Rental Fees"){entry.revenue+=amount;entry.income+=amount}});[...cateringRecords,...uniformRecords].forEach(record=>{const monthKey=String(record.month||"").slice(0,7);if(!monthKey)return;const entry=getEntry(monthKey),amount=toNumber(record.amount);if(record.metric==="Sales")entry.revenue+=amount;if(record.metric==="Commission")entry.income+=amount});return [...grouped.values()].map(item=>{const date=new Date(`${item.month}-01T00:00:00`);return {...item,label:new Intl.DateTimeFormat("en-GB",{month:"short"}).format(date),monthNumber:date.getMonth()+1}}).sort((a,b)=>MONTH_ORDER.indexOf(a.monthNumber)-MONTH_ORDER.indexOf(b.monthNumber))}
function getContractHealth(){const providers=Object.values(providerSource.providers||{}),today=new Date(),warningDate=new Date(today);warningDate.setDate(warningDate.getDate()+90);let active=0,expiring=0,expired=0,notRecorded=0;providers.forEach(provider=>{const contract=provider.contract||{},storedStatus=String(contract.status||"").toLowerCase(),expiryDate=contract.expiryDate?new Date(`${contract.expiryDate}T23:59:59`):null;if(storedStatus.includes("cancel")||storedStatus.includes("no active")||storedStatus.includes("expired")){expired+=1;return}if(!expiryDate||Number.isNaN(expiryDate.getTime())){if(storedStatus==="active")active+=1;else notRecorded+=1;return}if(expiryDate<today)expired+=1;else if(expiryDate<=warningDate)expiring+=1;else active+=1});return {total:providers.length,active,expiring,expired,notRecorded}}
function RevenueMixTooltip({active,payload}){if(!active||!payload||payload.length===0)return null;const item=payload[0]?.payload;if(!item)return null;return <div className="dashboard-donut-tooltip"><span>{item.name}</span><strong>{formatCurrency(item.revenue)}</strong><small>{formatPercent(item.contribution)}</small></div>}

export default function DashboardPage(){
 const {setHeaderControls}=useOutletContext();
 const leasingRecords=Array.isArray(leasingSource.records)?leasingSource.records:[];
 const cateringRecords=Array.isArray(cateringSource.records)?cateringSource.records:[];
 const uniformRecords=Array.isArray(uniformSource.records)?uniformSource.records:[];
 const academicYears=useMemo(()=>unique([...leasingRecords.map(r=>r.academicYear),...cateringRecords.map(r=>r.academicYear),...uniformRecords.map(r=>r.academicYear)]).sort((a,b)=>b.localeCompare(a)),[leasingRecords,cateringRecords,uniformRecords]);
 const [academicYear,setAcademicYear]=useState(()=>getLatestAcademicYear(academicYears));
 const [schoolFilter,setSchoolFilter]=useState("");
 useEffect(()=>{setHeaderControls(<div className="header-page-filters"><div className="header-filter-control"><label htmlFor="dashboard-academic-year">Academic year</label><select id="dashboard-academic-year" value={academicYear} onChange={e=>setAcademicYear(e.target.value)}>{academicYears.map(year=><option key={year} value={year}>{year}</option>)}</select></div><div className="header-filter-control wide"><label htmlFor="dashboard-school">School</label><select id="dashboard-school" value={schoolFilter} onChange={e=>setSchoolFilter(e.target.value)}><option value="">All Schools</option><option value="Repton Dubai">Repton Dubai</option><option value="Repton Al Barsha">Repton Al Barsha</option><option value="Repton Fry">Repton Fry</option><option value="Repton Rose">Repton Rose</option></select></div></div>);return()=>setHeaderControls(null)},[academicYear,academicYears,schoolFilter,setHeaderControls]);
 const filteredLeasing=useMemo(()=>leasingRecords.filter(r=>(!academicYear||r.academicYear===academicYear)&&(!schoolFilter||getSchoolLabel(r.school)===schoolFilter)),[academicYear,schoolFilter,leasingRecords]);
 const filteredCatering=useMemo(()=>cateringRecords.filter(r=>(!academicYear||r.academicYear===academicYear)&&(!schoolFilter||getSchoolLabel(r.schoolName||r.school)===schoolFilter)&&r.scenario==="Actual"),[academicYear,schoolFilter,cateringRecords]);
 const filteredUniform=useMemo(()=>uniformRecords.filter(r=>(!academicYear||r.academicYear===academicYear)&&(!schoolFilter||getSchoolLabel(r.schoolName||r.school)===schoolFilter)&&r.scenario==="Actual"),[academicYear,schoolFilter,uniformRecords]);
 const streamData=useMemo(()=>{const leasing=getLeasingSummary(filteredLeasing),catering=getSalesCommissionSummary(filteredCatering),uniform=getSalesCommissionSummary(filteredUniform);const result=[{name:"Leasing",description:"Programmes and facility income",path:"/leasing/programmes",...leasing},{name:"Catering",description:"Food-service sales and commission",path:"/catering",...catering},{name:"Uniform",description:"Uniform sales and commission",path:"/uniform",...uniform}];const totalRevenue=result.reduce((sum,item)=>sum+item.revenue,0);return result.map(item=>({...item,contribution:totalRevenue>0?(item.revenue/totalRevenue)*100:0}))},[filteredLeasing,filteredCatering,filteredUniform]);
 const totalRevenue=streamData.reduce((sum,item)=>sum+item.revenue,0),totalIncome=streamData.reduce((sum,item)=>sum+item.income,0);
 const schoolData=useMemo(()=>buildSchoolData({leasingRecords:filteredLeasing,cateringRecords:filteredCatering,uniformRecords:filteredUniform}),[filteredLeasing,filteredCatering,filteredUniform]);
 const monthlyData=useMemo(()=>buildMonthlyTrend({leasingRecords:filteredLeasing,cateringRecords:filteredCatering,uniformRecords:filteredUniform}),[filteredLeasing,filteredCatering,filteredUniform]);
 const contractHealth=useMemo(()=>getContractHealth(),[]),schoolsCount=unique(schoolData.map(item=>item.school)).length;
 return <section className="commercial-dashboard-page">
  <section className="dashboard-overview-strip"><article className="dashboard-primary-metric"><div className="dashboard-metric-label"><span>Commercial revenue</span><b>Selected period</b></div><strong>{formatCurrency(totalRevenue)}</strong><div className="dashboard-metric-footer"><span>Across Leasing, Catering and Uniform</span><i>{streamData.length} streams</i></div></article><article className="dashboard-secondary-metric"><span>School income</span><strong>{formatCurrency(totalIncome)}</strong><small>Commission and leasing income</small></article><article className="dashboard-secondary-metric"><span>Income yield</span><strong>{formatPercent(totalRevenue>0?(totalIncome/totalRevenue)*100:0)}</strong><small>School income as a share of revenue</small></article><article className="dashboard-secondary-metric"><span>Schools covered</span><strong>{schoolsCount}</strong><small>Schools represented in the selected year</small></article></section>
  <section className="dashboard-content-grid"><section className="dashboard-main-column">
   <article className="saas-panel dashboard-performance-panel"><div className="saas-panel-heading"><div><span className="saas-panel-kicker">Schools</span><h2>Performance by school</h2><p>Commercial revenue and school income by school.</p></div><span className="dashboard-count-pill">{academicYear}</span></div><div className="dashboard-chart-container dashboard-school-chart-container"><ResponsiveContainer width="100%" height="100%"><BarChart data={schoolData} margin={{top:12,right:10,left:2,bottom:24}}><CartesianGrid strokeDasharray="2 6" vertical={false} stroke="#e5e7eb"/><XAxis dataKey="school" tick={{fontSize:10}} interval={0} axisLine={false} tickLine={false}/><YAxis tick={{fontSize:10}} tickFormatter={formatCompactCurrency} axisLine={false} tickLine={false}/><Tooltip formatter={value=>formatCurrency(value)} contentStyle={{borderRadius:10,border:"1px solid #e5e7eb",boxShadow:"0 12px 30px rgba(15, 23, 42, 0.10)"}}/><Legend/><Bar dataKey="revenue" name="Commercial Revenue" fill="#111827" radius={[5,5,0,0]}/><Bar dataKey="income" name="School Income" fill="#8b5cf6" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div></article>
   <article className="saas-panel"><div className="saas-panel-heading"><div><span className="saas-panel-kicker">Revenue streams</span><h2>Business lines</h2><p>Open a stream to continue into its detailed operating view.</p></div></div><div className="dashboard-stream-list">{streamData.map(stream=><Link key={stream.name} to={stream.path} className="dashboard-stream-row"><div className="dashboard-stream-symbol" style={{"--stream-colour":STREAM_COLOURS[stream.name]}}>{stream.name.slice(0,1)}</div><div className="dashboard-stream-copy"><strong>{stream.name}</strong><span>{stream.description}</span></div><div className="dashboard-stream-value"><strong>{formatCurrency(stream.revenue)}</strong><span>{formatPercent(stream.contribution)} of revenue</span></div><div className="dashboard-stream-income"><span>School income</span><strong>{formatCurrency(stream.income)}</strong></div><span className="dashboard-stream-chevron">→</span></Link>)}</div></article>
   <article className="saas-panel"><div className="saas-panel-heading"><div><span className="saas-panel-kicker">Performance</span><h2>Monthly revenue</h2><p>Combined commercial revenue and school income from September to August.</p></div></div><div className="dashboard-line-container"><ResponsiveContainer width="100%" height="100%"><LineChart data={monthlyData} margin={{top:14,right:18,left:4,bottom:4}}><CartesianGrid strokeDasharray="2 6" vertical={false} stroke="#e5e7eb"/><XAxis dataKey="label" tick={{fontSize:11}} axisLine={false} tickLine={false}/><YAxis tick={{fontSize:10}} tickFormatter={formatCompactCurrency} axisLine={false} tickLine={false}/><Tooltip formatter={value=>formatCurrency(value)} contentStyle={{borderRadius:10,border:"1px solid #e5e7eb",boxShadow:"0 12px 30px rgba(15, 23, 42, 0.10)"}}/><Legend/><Line type="monotone" dataKey="revenue" name="Commercial Revenue" stroke="#111827" strokeWidth={2.5} dot={false} activeDot={{r:4}}/><Line type="monotone" dataKey="income" name="School Income" stroke="#7c3aed" strokeWidth={2.5} dot={false} activeDot={{r:4}}/></LineChart></ResponsiveContainer></div></article>
  </section><aside className="dashboard-side-column">
   <article className="saas-panel dashboard-breakdown-panel"><div className="saas-panel-heading compact"><div><span className="saas-panel-kicker">Mix</span><h2>Revenue breakdown</h2></div></div><div className="dashboard-donut-wrap"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={streamData} dataKey="revenue" nameKey="name" innerRadius="63%" outerRadius="84%" paddingAngle={4} stroke="none">{streamData.map(item=><Cell key={item.name} fill={STREAM_COLOURS[item.name]}/>)}</Pie><Tooltip content={<RevenueMixTooltip/>} position={{x:6,y:6}} allowEscapeViewBox={{x:true,y:true}} wrapperStyle={{pointerEvents:"none",zIndex:5}}/></PieChart></ResponsiveContainer><div className="dashboard-donut-centre"><strong>{formatCompactCurrency(totalRevenue)}</strong><span>Total</span></div></div><div className="dashboard-breakdown-list">{streamData.map(stream=><div key={stream.name}><span style={{"--stream-colour":STREAM_COLOURS[stream.name]}}/><b>{stream.name}</b><strong>{formatPercent(stream.contribution)}</strong></div>)}</div></article>
   <article className="saas-panel"><div className="saas-panel-heading compact"><div><span className="saas-panel-kicker">Contracts</span><h2>Contract health</h2></div><span className="dashboard-count-pill">{contractHealth.total}</span></div><div className="contract-health-list"><div><span className="status-dot active"/><b>Active</b><strong>{contractHealth.active}</strong></div><div><span className="status-dot expiring"/><b>Expiring soon</b><strong>{contractHealth.expiring}</strong></div><div><span className="status-dot expired"/><b>Expired / inactive</b><strong>{contractHealth.expired}</strong></div><div><span className="status-dot unknown"/><b>Not recorded</b><strong>{contractHealth.notRecorded}</strong></div></div></article>
   <article className="saas-panel"><div className="saas-panel-heading compact"><div><span className="saas-panel-kicker">Shortcuts</span><h2>Quick access</h2></div></div><div className="dashboard-quick-links"><Link to="/leasing/programmes"><span>Leasing</span><strong>Programme Directory</strong><i>→</i></Link><Link to="/catering"><span>Catering</span><strong>Open dashboard</strong><i>→</i></Link><Link to="/uniform"><span>Uniform</span><strong>Open dashboard</strong><i>→</i></Link></div></article>
  </aside></section>
 </section>
}
