import { useEffect, useMemo, useState } from "react";
import { Link, useOutletContext } from "react-router-dom";
import { Bar, BarChart, CartesianGrid, Cell, Legend, Line, LineChart, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { fetchCommercialOverviewRecords } from "../../lib/commercialOverviewData";
import { fetchProviders } from "../../lib/providerData";
import "./DashboardPage.css";

const STREAM_META={
 leasing:{description:"Programmes and facility income",path:"/leasing/programmes",colour:"#6d5dfc"},
 catering:{description:"Food-service sales and commission",path:"/catering",colour:"#159f8c"},
 kitchen_rental:{description:"Annual kitchen rental income",path:"/catering/kitchen-rental",colour:"#0f766e"},
 uniform:{description:"Uniform sales and commission",path:"/uniform",colour:"#e97832"},
 photography:{description:"Photography sales and commission",path:"/photography",colour:"#2563eb"},
};
const FALLBACK_COLOURS=["#0891b2","#db2777","#ca8a04","#0f766e","#9333ea","#64748b"];
const MONTH_ORDER=[9,10,11,12,1,2,3,4,5,6,7,8];
function unique(values){return [...new Set(values.filter(Boolean))]}
function toNumber(value){const number=Number(value);return Number.isFinite(number)?number:0}
function formatCurrency(value){return new Intl.NumberFormat("en-AE",{style:"currency",currency:"AED",maximumFractionDigits:0}).format(toNumber(value))}
function formatCompactCurrency(value){return new Intl.NumberFormat("en-AE",{style:"currency",currency:"AED",notation:"compact",maximumFractionDigits:1}).format(toNumber(value))}
function formatPercent(value){return Number.isFinite(value)?`${value.toFixed(1)}%`:"—"}
function getLatestAcademicYear(years){return [...years].sort((a,b)=>b.localeCompare(a))[0]||""}
function getStreamMeta(code,index){const known=STREAM_META[code];return known||{description:"Commercial revenue stream",path:"#",colour:FALLBACK_COLOURS[index%FALLBACK_COLOURS.length]}}
function getMetricRole(record){const code=String(record.metricCode||"").toLowerCase();if(code==="sales"||code==="revenue")return"revenue";if(code==="commission")return"income";if(code==="rental_fees"||code==="rental-fees"||code==="rental fees")return"both";return"other"}
function buildStreamData(records){const grouped=new Map();records.forEach(record=>{const code=record.streamCode||String(record.streamName||"stream").toLowerCase();if(!grouped.has(code))grouped.set(code,{code,name:record.streamName||code,revenue:0,income:0});const item=grouped.get(code),amount=toNumber(record.amount),role=getMetricRole(record);if(role==="revenue")item.revenue+=amount;if(role==="income")item.income+=amount;if(role==="both"){item.revenue+=amount;item.income+=amount}});const result=[...grouped.values()].filter(item=>item.revenue!==0||item.income!==0).sort((a,b)=>b.revenue-a.revenue).map((item,index)=>({...item,...getStreamMeta(item.code,index)}));const total=result.reduce((sum,item)=>sum+item.revenue,0);return result.map(item=>({...item,contribution:total>0?(item.revenue/total)*100:0}))}
function buildSchoolData(records){const grouped=new Map();records.forEach(record=>{const school=record.schoolName||record.schoolCode||"Unknown";if(!grouped.has(school))grouped.set(school,{school,revenue:0,income:0});const item=grouped.get(school),amount=toNumber(record.amount),role=getMetricRole(record);if(role==="revenue")item.revenue+=amount;if(role==="income")item.income+=amount;if(role==="both"){item.revenue+=amount;item.income+=amount}});return[...grouped.values()].sort((a,b)=>b.revenue-a.revenue)}
function getMonthInfo(month){const match=String(month||"").match(/^(\d{4})-(\d{2})/);if(!match)return null;const year=Number(match[1]),monthNumber=Number(match[2]);if(!year||!monthNumber)return null;const date=new Date(Date.UTC(year,monthNumber-1,1));return{key:`${year}-${String(monthNumber).padStart(2,"0")}`,label:new Intl.DateTimeFormat("en-GB",{month:"short",timeZone:"UTC"}).format(date),monthNumber}}
function buildMonthlyTrend(records){const grouped=new Map();records.forEach(record=>{const info=getMonthInfo(record.month);if(!info)return;if(!grouped.has(info.key))grouped.set(info.key,{month:info.key,label:info.label,monthNumber:info.monthNumber,revenue:0,income:0});const item=grouped.get(info.key),amount=toNumber(record.amount),role=getMetricRole(record);if(role==="revenue")item.revenue+=amount;if(role==="income")item.income+=amount;if(role==="both"){item.revenue+=amount;item.income+=amount}});return[...grouped.values()].sort((a,b)=>MONTH_ORDER.indexOf(a.monthNumber)-MONTH_ORDER.indexOf(b.monthNumber))}
function getContractHealth(providers=[]){const today=new Date(),warningDate=new Date(today);warningDate.setDate(warningDate.getDate()+90);let active=0,expiring=0,expired=0,notRecorded=0;providers.forEach(provider=>{const contract=provider.contract||{},storedStatus=String(contract.status||"").toLowerCase(),expiryDate=contract.expiryDate?new Date(`${contract.expiryDate}T23:59:59`):null;if(storedStatus.includes("cancel")||storedStatus.includes("no active")||storedStatus.includes("expired")){expired+=1;return}if(!expiryDate||Number.isNaN(expiryDate.getTime())){if(storedStatus==="active")active+=1;else notRecorded+=1;return}if(expiryDate<today)expired+=1;else if(expiryDate<=warningDate)expiring+=1;else active+=1});return{total:providers.length,active,expiring,expired,notRecorded}}
function RevenueMixTooltip({active,payload}){if(!active||!payload||payload.length===0)return null;const item=payload[0]?.payload;if(!item)return null;return <div className="dashboard-donut-tooltip"><span>{item.name}</span><strong>{formatCurrency(item.revenue)}</strong><small>{formatPercent(item.contribution)}</small></div>}

export default function DashboardPage(){
 const{setHeaderControls}=useOutletContext();
 const[records,setRecords]=useState([]),[providers,setProviders]=useState([]),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState(""),[academicYear,setAcademicYear]=useState(""),[schoolFilter,setSchoolFilter]=useState("");
 useEffect(()=>{let active=true;async function load(){setLoading(true);setLoadError("");try{const commercialRecords=await fetchCommercialOverviewRecords();if(!active)return;setRecords(commercialRecords);const years=unique(commercialRecords.map(r=>r.academicYear)).sort((a,b)=>b.localeCompare(a));setAcademicYear(current=>current||getLatestAcademicYear(years));try{const providerData=await fetchProviders({force:true});if(active)setProviders(providerData)}catch(providerError){console.error("Unable to load contract health data",providerError);if(active)setProviders([])}}catch(error){if(active){console.error("Unable to load Commercial Overview financial data from Supabase",error);setLoadError(error?.message||"Unable to load Commercial Overview data from Supabase.")}}finally{if(active)setLoading(false)}}load();return()=>{active=false}},[]);
 const academicYears=useMemo(()=>unique(records.map(r=>r.academicYear)).sort((a,b)=>b.localeCompare(a)),[records]);
 const availableSchools=useMemo(()=>unique(records.map(r=>r.schoolName||r.schoolCode)).sort((a,b)=>a.localeCompare(b)),[records]);
 useEffect(()=>{setHeaderControls(<div className="header-page-filters"><div className="header-filter-control"><label htmlFor="dashboard-academic-year">Academic year</label><select id="dashboard-academic-year" value={academicYear} onChange={e=>setAcademicYear(e.target.value)}>{academicYears.map(year=><option key={year} value={year}>{year}</option>)}</select></div><div className="header-filter-control wide"><label htmlFor="dashboard-school">School</label><select id="dashboard-school" value={schoolFilter} onChange={e=>setSchoolFilter(e.target.value)}><option value="">All Schools</option>{availableSchools.map(school=><option key={school} value={school}>{school}</option>)}</select></div></div>);return()=>setHeaderControls(null)},[academicYear,academicYears,availableSchools,schoolFilter,setHeaderControls]);
 const filteredRecords=useMemo(()=>records.filter(r=>(!academicYear||r.academicYear===academicYear)&&(!schoolFilter||(r.schoolName||r.schoolCode)===schoolFilter)&&r.scenario==="Actual"),[academicYear,schoolFilter,records]);
 const streamData=useMemo(()=>buildStreamData(filteredRecords),[filteredRecords]);
 const totalRevenue=streamData.reduce((sum,item)=>sum+item.revenue,0),totalIncome=streamData.reduce((sum,item)=>sum+item.income,0);
 const schoolData=useMemo(()=>buildSchoolData(filteredRecords),[filteredRecords]);
 const monthlyData=useMemo(()=>buildMonthlyTrend(filteredRecords),[filteredRecords]);
 const contractHealth=useMemo(()=>getContractHealth(providers),[providers]),schoolsCount=unique(schoolData.map(item=>item.school)).length;
 const streamNames=streamData.map(item=>item.name).join(", ");
 if(loading)return <section className="commercial-dashboard-page"><div className="dashboard-empty-state">Loading Commercial Overview…</div></section>;
 if(loadError)return <section className="commercial-dashboard-page"><div className="dashboard-empty-state">{loadError}</div></section>;
 return <section className="commercial-dashboard-page">
  <section className="dashboard-overview-strip"><article className="dashboard-primary-metric"><div className="dashboard-metric-label"><span>Commercial revenue</span><b>Selected period</b></div><strong>{formatCurrency(totalRevenue)}</strong><div className="dashboard-metric-footer"><span>Across {streamNames||"commercial revenue streams"}</span><i>{streamData.length} streams</i></div></article><article className="dashboard-secondary-metric"><span>School income</span><strong>{formatCurrency(totalIncome)}</strong><small>Commission and other commercial income</small></article><article className="dashboard-secondary-metric"><span>Income yield</span><strong>{formatPercent(totalRevenue>0?(totalIncome/totalRevenue)*100:0)}</strong><small>School income as a share of revenue</small></article><article className="dashboard-secondary-metric"><span>Schools covered</span><strong>{schoolsCount}</strong><small>Schools represented in the selected year</small></article></section>
  <section className="dashboard-content-grid"><section className="dashboard-main-column">
   <article className="saas-panel dashboard-performance-panel"><div className="saas-panel-heading"><div><span className="saas-panel-kicker">Schools</span><h2>Performance by school</h2><p>Commercial revenue and school income by school.</p></div><span className="dashboard-count-pill">{academicYear}</span></div><div className="dashboard-chart-container dashboard-school-chart-container"><ResponsiveContainer width="100%" height="100%"><BarChart data={schoolData} margin={{top:12,right:10,left:2,bottom:24}}><CartesianGrid strokeDasharray="2 6" vertical={false} stroke="#e5e7eb"/><XAxis dataKey="school" tick={{fontSize:10}} interval={0} axisLine={false} tickLine={false}/><YAxis tick={{fontSize:10}} tickFormatter={formatCompactCurrency} axisLine={false} tickLine={false}/><Tooltip formatter={value=>formatCurrency(value)}/><Legend/><Bar dataKey="revenue" name="Commercial Revenue" fill="#111827" radius={[5,5,0,0]}/><Bar dataKey="income" name="School Income" fill="#8b5cf6" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div></article>
   <article className="saas-panel"><div className="saas-panel-heading"><div><span className="saas-panel-kicker">Revenue streams</span><h2>Business lines</h2><p>Open a stream to continue into its detailed operating view.</p></div></div><div className="dashboard-stream-list">{streamData.map(stream=><Link key={stream.code} to={stream.path} className="dashboard-stream-row"><div className="dashboard-stream-symbol" style={{"--stream-colour":stream.colour}}>{stream.name.slice(0,1)}</div><div className="dashboard-stream-copy"><strong>{stream.name}</strong><span>{stream.description}</span></div><div className="dashboard-stream-value"><strong>{formatCurrency(stream.revenue)}</strong><span>{formatPercent(stream.contribution)} of revenue</span></div><div className="dashboard-stream-income"><span>School income</span><strong>{formatCurrency(stream.income)}</strong></div><span className="dashboard-stream-chevron">→</span></Link>)}</div></article>
   <article className="saas-panel"><div className="saas-panel-heading"><div><span className="saas-panel-kicker">Performance</span><h2>Monthly revenue</h2><p>Combined commercial revenue and school income from September to August.</p></div></div><div className="dashboard-line-container"><ResponsiveContainer width="100%" height="100%"><LineChart data={monthlyData} margin={{top:14,right:18,left:4,bottom:4}}><CartesianGrid strokeDasharray="2 6" vertical={false} stroke="#e5e7eb"/><XAxis dataKey="label" tick={{fontSize:11}} axisLine={false} tickLine={false}/><YAxis tick={{fontSize:10}} tickFormatter={formatCompactCurrency} axisLine={false} tickLine={false}/><Tooltip formatter={value=>formatCurrency(value)}/><Legend/><Line type="monotone" dataKey="revenue" name="Commercial Revenue" stroke="#111827" strokeWidth={2.5} dot={false}/><Line type="monotone" dataKey="income" name="School Income" stroke="#7c3aed" strokeWidth={2.5} dot={false}/></LineChart></ResponsiveContainer></div></article>
  </section><aside className="dashboard-side-column">
   <article className="saas-panel dashboard-breakdown-panel"><div className="saas-panel-heading compact"><div><span className="saas-panel-kicker">Mix</span><h2>Revenue breakdown</h2></div></div><div className="dashboard-donut-wrap"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={streamData} dataKey="revenue" nameKey="name" innerRadius="63%" outerRadius="84%" paddingAngle={4} stroke="none">{streamData.map(item=><Cell key={item.code} fill={item.colour}/>)}</Pie><Tooltip content={<RevenueMixTooltip/>}/></PieChart></ResponsiveContainer><div className="dashboard-donut-centre"><strong>{formatCompactCurrency(totalRevenue)}</strong><span>Total</span></div></div><div className="dashboard-breakdown-list">{streamData.map(stream=><div key={stream.code}><span style={{"--stream-colour":stream.colour}}/><b>{stream.name}</b><strong>{formatPercent(stream.contribution)}</strong></div>)}</div></article>
   <article className="saas-panel"><div className="saas-panel-heading compact"><div><span className="saas-panel-kicker">Contracts</span><h2>Contract health</h2></div><span className="dashboard-count-pill">{contractHealth.total}</span></div><div className="contract-health-list"><div><span className="status-dot active"/><b>Active</b><strong>{contractHealth.active}</strong></div><div><span className="status-dot expiring"/><b>Expiring soon</b><strong>{contractHealth.expiring}</strong></div><div><span className="status-dot expired"/><b>Expired / inactive</b><strong>{contractHealth.expired}</strong></div><div><span className="status-dot unknown"/><b>Not recorded</b><strong>{contractHealth.notRecorded}</strong></div></div></article>
   <article className="saas-panel"><div className="saas-panel-heading compact"><div><span className="saas-panel-kicker">Shortcuts</span><h2>Quick access</h2></div></div><div className="dashboard-quick-links">{streamData.filter(stream=>stream.path!=="#").map(stream=><Link key={stream.code} to={stream.path}><span>{stream.name}</span><strong>{stream.code==="leasing"?"Programme Directory":"Open dashboard"}</strong><i>→</i></Link>)}</div></article>
  </aside></section>
 </section>
}
