import { useEffect,useMemo,useState } from "react";
import { useOutletContext } from "react-router-dom";
import { Bar,BarChart,CartesianGrid,Legend,ResponsiveContainer,Tooltip,XAxis,YAxis } from "recharts";
import DashboardCurrencyTooltip from "../../components/dashboard/DashboardCurrencyTooltip";import KpiCard from "../../components/dashboard/KpiCard";import ManageRecordsLink from "../../components/dashboard/ManageRecordsLink";import MonthlyResultsTable from "../../components/dashboard/MonthlyResultsTable";import MonthlyTrendChart from "../../components/dashboard/MonthlyTrendChart";import MetricToggle from "../../components/dashboard/MetricToggle";
import "../../components/dashboard/dashboardComponents.css";import "../catering/CateringDashboardPage.css";import "./TransportCostCentrePage.css";
import {fetchTransportCostRecords,filterTransportCostRecords,formatCompactCurrency,formatCurrency,getMonthlyTransportCostData,getSchoolTransportCostData,getTransportCostAcademicYears,getTransportCostSchools,getTransportCostSummary} from "../../lib/transportCostData";
function TripCostDetail({row}){const items=[["Day Trips",row.dayTrips],["Sports Trips",row.sportsTrips],["Boarding Trips",row.boardingTrips],["Other Trips",row.otherTrips]];return <div className="transport-trip-detail"><div className="transport-trip-detail-heading"><strong>Trip Cost Breakdown</strong><span>{row.label} · {row.academicYear}</span></div><table><thead><tr><th>Trip Type</th><th>Cost</th></tr></thead><tbody>{items.map(([label,value])=><tr key={label}><td>{label}</td><td>{formatCurrency(value)}</td></tr>)}</tbody><tfoot><tr><th>Total Trip Costs</th><th>{formatCurrency(row.tripCosts)}</th></tr></tfoot></table></div>}
function SchoolCostChart({data,tooltip,metric}){const configurations={overview:[{key:"tripCosts",label:"Trip Costs",fill:"#2563eb",stackId:"total"},{key:"contractualCosts",label:"Contractual Costs",fill:"#0f766e",stackId:"total"}],total:[{key:"totalCost",label:"Total Cost",fill:"#2563eb"}],trips:[{key:"tripCosts",label:"Trip Costs",fill:"#d97706"}],contractual:[{key:"contractualCosts",label:"Contractual Costs",fill:"#0f766e"}]};const series=configurations[metric]||configurations.overview;return <div className="dashboard-chart-canvas" style={{height:290}}><ResponsiveContainer width="100%" height="100%"><BarChart data={data} margin={{top:10,right:10,left:24,bottom:5}} barCategoryGap="34%"><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="school" tickLine={false} axisLine={false}/><YAxis tickFormatter={formatCompactCurrency} tickLine={false} axisLine={false} width={84}/><Tooltip content={tooltip}/><Legend/>{series.map((item,index)=><Bar key={item.key} dataKey={item.key} name={item.label} stackId={item.stackId} fill={item.fill} radius={item.stackId&&index===0?[0,0,0,0]:[5,5,0,0]}/>)}</BarChart></ResponsiveContainer></div>}
export default function TransportCostCentrePage(){
 const{setHeaderControls}=useOutletContext(),[records,setRecords]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[filters,setFilters]=useState({academicYear:"",school:"",scenario:"Actual"}),[analysisView,setAnalysisView]=useState("school"),[schoolMetric,setSchoolMetric]=useState("overview");
 useEffect(()=>{let active=true;(async()=>{try{setLoading(true);setError("");const nextRecords=await fetchTransportCostRecords();if(!active)return;setRecords(nextRecords);const years=getTransportCostAcademicYears(nextRecords);setFilters(c=>({...c,academicYear:c.academicYear||years[years.length-1]||""}))}catch(e){if(active)setError(e?.message||"Unable to load Transport Cost Centre.")}finally{if(active)setLoading(false)}})();return()=>{active=false}},[]);
 const years=useMemo(()=>getTransportCostAcademicYears(records),[records]),schools=useMemo(()=>getTransportCostSchools(records),[records]),filtered=useMemo(()=>filterTransportCostRecords(records,filters),[records,filters]),summary=useMemo(()=>getTransportCostSummary(filtered),[filtered]),monthly=useMemo(()=>getMonthlyTransportCostData(filtered),[filtered]),schoolData=useMemo(()=>getSchoolTransportCostData(filtered),[filtered]),tooltip=<DashboardCurrencyTooltip formatValue={formatCurrency}/>;
 useEffect(()=>{setHeaderControls(<div className="header-page-filters"><label className="header-filter-control"><span>Academic Year</span><select value={filters.academicYear} onChange={e=>setFilters(c=>({...c,academicYear:e.target.value}))}><option value="">All Years</option>{years.map(y=><option key={y}>{y}</option>)}</select></label><label className="header-filter-control wide"><span>School</span><select value={filters.school} onChange={e=>setFilters(c=>({...c,school:e.target.value}))}><option value="">All Schools</option>{schools.map(s=><option key={s.code} value={s.code}>{s.name}</option>)}</select></label><label className="header-filter-control"><span>Scenario</span><select value={filters.scenario} onChange={e=>setFilters(c=>({...c,scenario:e.target.value}))}>{["Actual","Budget","Forecast"].map(x=><option key={x}>{x}</option>)}</select></label></div>);return()=>setHeaderControls(null)},[filters,years,schools,setHeaderControls]);
 if(loading)return <section className="dashboard-page"><div className="dashboard-loading-state">Loading Transport Cost Centre…</div></section>;if(error)return <section className="dashboard-page"><div className="dashboard-error-state">{error}</div></section>;
 const columns=[{key:"academicYear",label:"Academic Year"},{key:"label",label:"Month"},{key:"term",label:"Term"},{key:"tripCosts",label:"Trip Costs",numeric:true,render:(value,row,controls)=><button type="button" className="transport-cost-drilldown" onClick={controls.toggle} aria-expanded={controls.expanded}>{formatCurrency(value)}<span className={`transport-drilldown-chevron ${controls.expanded?"expanded":""}`}>›</span></button>},{key:"supplementalFees",label:"Supplemental Fees",numeric:true,render:formatCurrency},{key:"busGuardianFees",label:"Bus Guardian Fees",numeric:true,render:formatCurrency},{key:"capacityShortfall",label:"Capacity Shortfall",numeric:true,render:formatCurrency},{key:"otherCharges",label:"Other Charges",numeric:true,render:formatCurrency},{key:"totalCost",label:"Total Cost",numeric:true,render:formatCurrency}];
 const trendMetrics=[{key:"totalCost",label:"Total Cost",tone:"primary"},{key:"tripCosts",label:"Trip Costs",tone:"secondary"},{key:"contractualCosts",label:"Contractual Costs",tone:"tertiary"},{key:"otherCharges",label:"Other Charges",tone:"quaternary"}];
 return <section className="dashboard-page"><section className="dashboard-kpi-grid"><KpiCard label="Total Cost" value={formatCurrency(summary.totalCost)} detail={`${summary.schools} schools · ${summary.months} months`}/><KpiCard label="Trip Costs" value={formatCurrency(summary.tripCosts)} detail="Day, sports, boarding and other trips"/><KpiCard label="Contractual Costs" value={formatCurrency(summary.contractualCosts)} detail="Supplemental, guardian, staff transport and capacity shortfall"/><KpiCard label="Capacity Shortfall" value={formatCurrency(summary.capacityShortfall)} detail="Contractual cost shown separately for visibility"/></section><section className="dashboard-wide-card transport-analysis-card"><div className="transport-primary-tabs"><button className={analysisView==="school"?"active":""} onClick={()=>setAnalysisView("school")}>Cost by School</button><button className={analysisView==="trend"?"active":""} onClick={()=>setAnalysisView("trend")}>Monthly Trend</button></div><div className="transport-analysis-heading"><div><h2>{analysisView==="school"?"Cost by School":"Monthly Trend"}</h2><p>{analysisView==="school"?"Total transport cost composition by school.":"Monthly movement of transport costs across the selected reporting scope."}</p></div>{analysisView==="school"?<MetricToggle options={[{value:"overview",label:"Overview"},{value:"total",label:"Total Cost"},{value:"trips",label:"Trip Costs"},{value:"contractual",label:"Contractual Costs"}]} value={schoolMetric} onChange={setSchoolMetric} ariaLabel="Cost by school metric"/>:null}</div>{analysisView==="school"?<SchoolCostChart data={schoolData} tooltip={tooltip} metric={schoolMetric}/>:<MonthlyTrendChart data={monthly} metrics={trendMetrics} defaultMetric="Total Cost" formatAxis={formatCompactCurrency} tooltipContent={tooltip} className="transport-embedded-trend"/>}</section><MonthlyResultsTable data={monthly} columns={columns} totals={{tripCosts:formatCurrency(summary.tripCosts),supplementalFees:formatCurrency(summary.supplementalFees),busGuardianFees:formatCurrency(summary.busGuardianFees),capacityShortfall:formatCurrency(summary.capacityShortfall),otherCharges:formatCurrency(summary.otherCharges),totalCost:formatCurrency(summary.totalCost)}} renderExpandedRow={row=><TripCostDetail row={row}/>} emptyMessage="No Transport cost records match the selected filters." resetKey={`${filters.academicYear}|${filters.school}|${filters.scenario}`}/><ManageRecordsLink label="Manage Transport Costs" to="/financial-records?area=cost-centres&costCentre=transport&view=register" description="Review or update the cost records behind the Transport Cost Centre."/></section>
}
