import { useEffect, useMemo, useState } from "react";
import { useOutletContext } from "react-router-dom";
import DashboardCurrencyTooltip from "../../components/dashboard/DashboardCurrencyTooltip";
import KpiCard from "../../components/dashboard/KpiCard";
import ManageRecordsLink from "../../components/dashboard/ManageRecordsLink";
import MonthlyResultsTable from "../../components/dashboard/MonthlyResultsTable";
import MonthlyTrendChart from "../../components/dashboard/MonthlyTrendChart";
import PerformanceChart from "../../components/dashboard/PerformanceChart";
import "../../components/dashboard/dashboardComponents.css";
import "../catering/CateringDashboardPage.css";
import "./TransportCostCentrePage.css";
import { fetchTransportCostRecords,filterTransportCostRecords,formatCompactCurrency,formatCurrency,getMonthlyTransportCostData,getSchoolTransportCostData,getTransportCostAcademicYears,getTransportCostSchools,getTransportCostSummary } from "../../lib/transportCostData";
export default function TransportCostCentrePage(){
 const {setHeaderControls}=useOutletContext(),[records,setRecords]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[filters,setFilters]=useState({academicYear:"",school:"",scenario:"Actual"});
 useEffect(()=>{let active=true;(async()=>{try{setLoading(true);setError("");const nextRecords=await fetchTransportCostRecords();if(!active)return;setRecords(nextRecords);const years=getTransportCostAcademicYears(nextRecords);setFilters(c=>({...c,academicYear:c.academicYear||years[years.length-1]||""}))}catch(e){if(active)setError(e?.message||"Unable to load Transport Cost Centre.")}finally{if(active)setLoading(false)}})();return()=>{active=false}},[]);
 const years=useMemo(()=>getTransportCostAcademicYears(records),[records]),schools=useMemo(()=>getTransportCostSchools(records),[records]),filtered=useMemo(()=>filterTransportCostRecords(records,filters),[records,filters]),summary=useMemo(()=>getTransportCostSummary(filtered),[filtered]),monthly=useMemo(()=>getMonthlyTransportCostData(filtered),[filtered]),schoolData=useMemo(()=>getSchoolTransportCostData(filtered),[filtered]),tooltip=<DashboardCurrencyTooltip formatValue={formatCurrency}/>;
 useEffect(()=>{setHeaderControls(<div className="header-page-filters"><label className="header-filter-control"><span>Academic Year</span><select value={filters.academicYear} onChange={e=>setFilters(c=>({...c,academicYear:e.target.value}))}><option value="">All Years</option>{years.map(y=><option key={y}>{y}</option>)}</select></label><label className="header-filter-control wide"><span>School</span><select value={filters.school} onChange={e=>setFilters(c=>({...c,school:e.target.value}))}><option value="">All Schools</option>{schools.map(s=><option key={s.code} value={s.code}>{s.name}</option>)}</select></label><label className="header-filter-control"><span>Scenario</span><select value={filters.scenario} onChange={e=>setFilters(c=>({...c,scenario:e.target.value}))}>{["Actual","Budget","Forecast"].map(x=><option key={x}>{x}</option>)}</select></label></div>);return()=>setHeaderControls(null)},[filters,years,schools,setHeaderControls]);
 if(loading)return <section className="dashboard-page"><div className="dashboard-loading-state">Loading Transport Cost Centre…</div></section>;if(error)return <section className="dashboard-page"><div className="dashboard-error-state">{error}</div></section>;
 const columns=[{key:"academicYear",label:"Academic Year"},{key:"label",label:"Month"},{key:"term",label:"Term"},{key:"tripCosts",label:"Trip Costs",numeric:true,render:formatCurrency},{key:"contractualCosts",label:"Contractual Costs",numeric:true,render:formatCurrency},{key:"otherCharges",label:"Other Charges",numeric:true,render:formatCurrency},{key:"offsets",label:"Subsidies / Credits",numeric:true,render:formatCurrency},{key:"netCost",label:"Net Cost",numeric:true,render:formatCurrency}];
 return <section className="dashboard-page"><section className="dashboard-kpi-grid"><KpiCard label="Net Transport Cost" value={formatCurrency(summary.netCost)} detail={`${summary.schools} schools · ${summary.months} months`}/><KpiCard label="Trip Costs" value={formatCurrency(summary.tripCosts)} detail="Day, sports, boarding and other trips"/><KpiCard label="Contractual Costs" value={formatCurrency(summary.contractualCosts)} detail="Contract and utilisation charges"/><KpiCard label="Other Charges" value={formatCurrency(summary.otherCharges)} detail={`Before ${formatCurrency(summary.offsets)} subsidies / credits`}/></section><section className="dashboard-two-column-grid"><PerformanceChart title="Cost by School" description="Transport cost composition by school." data={schoolData} categoryKey="school" metrics={[{key:"tripCosts",label:"Trip Costs",tone:"primary"},{key:"contractualCosts",label:"Contractual Costs",tone:"secondary"},{key:"otherCharges",label:"Other Charges",tone:"tertiary"}]} formatAxis={formatCompactCurrency} formatValue={formatCurrency} tooltipContent={tooltip}/><PerformanceChart title="School Net Cost" description="Net transport cost after subsidies and credits." data={schoolData} categoryKey="school" metrics={[{key:"netCost",label:"Net Cost",tone:"primary"}]} defaultMetric="Net Cost" formatAxis={formatCompactCurrency} formatValue={formatCurrency} tooltipContent={tooltip}/></section><MonthlyTrendChart data={monthly} metrics={[{key:"netCost",label:"Net Cost",tone:"primary"},{key:"tripCosts",label:"Trip Costs",tone:"secondary"},{key:"contractualCosts",label:"Contractual Costs",tone:"tertiary"}]} defaultMetric="Net Cost" formatAxis={formatCompactCurrency} tooltipContent={tooltip} className="dashboard-wide-card"/><MonthlyResultsTable data={monthly} columns={columns} totals={{tripCosts:formatCurrency(summary.tripCosts),contractualCosts:formatCurrency(summary.contractualCosts),otherCharges:formatCurrency(summary.otherCharges),offsets:formatCurrency(summary.offsets),netCost:formatCurrency(summary.netCost)}} emptyMessage="No Transport cost records match the selected filters." resetKey={`${filters.academicYear}|${filters.school}|${filters.scenario}`}/><ManageRecordsLink label="Manage Transport Costs" to="/financial-records?area=cost-centres&costCentre=transport&view=register" description="Review or update the cost records behind the Transport Cost Centre."/></section>
}
