import { useEffect, useMemo, useState } from "react";
import { useOutletContext } from "react-router-dom";
import DashboardCurrencyTooltip from "../../components/dashboard/DashboardCurrencyTooltip";
import MonthlyResultsTable from "../../components/dashboard/MonthlyResultsTable";
import MonthlyTrendChart from "../../components/dashboard/MonthlyTrendChart";
import FixedRevenueComparison from "../../components/comparison/FixedRevenueComparison";
import "../../components/dashboard/dashboardComponents.css";
import { fetchKitchenRentalRecords } from "../../lib/kitchenRentalData";
import "./KitchenRentalPage.css";

const MONTH_ORDER=["Sep","Oct","Nov","Dec","Jan","Feb","Mar","Apr","May","Jun","Jul","Aug"];
const MONTH_NUMBER={Sep:9,Oct:10,Nov:11,Dec:12,Jan:1,Feb:2,Mar:3,Apr:4,May:5,Jun:6,Jul:7,Aug:8};
function formatCurrency(value){return new Intl.NumberFormat("en-AE",{style:"currency",currency:"AED",maximumFractionDigits:0}).format(Number(value||0))}
function formatCompactCurrency(value){return new Intl.NumberFormat("en-AE",{style:"currency",currency:"AED",notation:"compact",maximumFractionDigits:1}).format(Number(value||0))}
function formatDate(value){if(!value)return"—";return new Intl.DateTimeFormat("en-GB",{day:"2-digit",month:"short",year:"numeric"}).format(new Date(`${value}T00:00:00`))}
function currentAcademicYear(){const now=new Date(),start=now.getMonth()>=8?now.getFullYear():now.getFullYear()-1;return`AY${start}-${String(start+1).slice(-2)}`}
function reportingMonthCount(year){if(year!==currentAcademicYear())return 12;const month=new Date().getMonth();return month>=8?month-7:month+5}
function academicYearStart(year){const match=String(year||"").match(/^AY(\d{4})-/);return match?Number(match[1]):0}
function calendarMonthForAcademicYear(year,label){const start=academicYearStart(year),number=MONTH_NUMBER[label]||0;if(!start||!number)return"";return`${number>=9?start:start+1}-${String(number).padStart(2,"0")}`}
function displayMonth(raw){return raw?new Intl.DateTimeFormat("en-GB",{month:"short",year:"2-digit"}).format(new Date(`${raw}-01T00:00:00`)):""}
function combineRecords(items){const monthMap=new Map(),contractMap=new Map();items.forEach(item=>{item.months.forEach(row=>{const current=monthMap.get(row.month)||{...row,revenue:0};current.revenue+=Number(row.revenue||0);monthMap.set(row.month,current)});(item.contracts||[]).forEach(contract=>contractMap.set(`${contract.contractId}|${item.schoolCode}`,{...contract,school:item.school,schoolCode:item.schoolCode}))});return{vatRate:items.find(item=>item.vatRate)?.vatRate||0,contracts:[...contractMap.values()],months:[...monthMap.values()].sort((a,b)=>MONTH_ORDER.indexOf(a.month)-MONTH_ORDER.indexOf(b.month))}}
function recognisedForYear(items,academicYear){const year=combineRecords(items),count=Math.min(reportingMonthCount(academicYear),12);return year.months.slice(0,count).reduce((sum,row)=>sum+Number(row.revenue||0),0)}
function comparisonRecords(items){return items.flatMap(item=>item.months.map(row=>({academicYear:item.academicYear,month:calendarMonthForAcademicYear(item.academicYear,row.month),term:row.term,revenue:Number(row.revenue||0)})))}

export default function KitchenRentalPage(){
 const{setHeaderControls}=useOutletContext();const[records,setRecords]=useState([]),[loading,setLoading]=useState(true),[loadError,setLoadError]=useState(""),[filters,setFilters]=useState({academicYear:"",school:""});
 useEffect(()=>{let active=true;(async()=>{try{setLoading(true);setLoadError("");const data=await fetchKitchenRentalRecords();if(!active)return;setRecords(data);const next=[...new Set(data.map(item=>item.academicYear))].sort((a,b)=>b.localeCompare(a));setFilters(current=>({...current,academicYear:current.academicYear||next[0]||""}))}catch(error){console.error("Unable to load Kitchen Rental records from Supabase",error);if(active)setLoadError("Unable to load Kitchen Rental data from Supabase.")}finally{if(active)setLoading(false)}})();return()=>{active=false}},[]);
 const years=useMemo(()=>[...new Set(records.map(item=>item.academicYear))].sort((a,b)=>b.localeCompare(a)),[records]);
 const schools=useMemo(()=>{const map=new Map();records.forEach(item=>{if(item.schoolCode)map.set(item.schoolCode,item.school)});return[...map.entries()].map(([code,name])=>({code,name})).sort((a,b)=>a.name.localeCompare(b.name))},[records]);
 const scopeRecords=useMemo(()=>records.filter(item=>!filters.school||item.schoolCode===filters.school),[records,filters.school]);
 useEffect(()=>{setHeaderControls(<div className="header-page-filters"><label className="header-filter-control"><span>Academic Year</span><select value={filters.academicYear} onChange={e=>setFilters(c=>({...c,academicYear:e.target.value}))}><option value="">All Years</option>{years.map(year=><option key={year} value={year}>{year}</option>)}</select></label><label className="header-filter-control wide"><span>School</span><select value={filters.school} onChange={e=>setFilters(c=>({...c,school:e.target.value}))}><option value="">All Schools</option>{schools.map(s=><option key={s.code} value={s.code}>{s.name}</option>)}</select></label></div>);return()=>setHeaderControls(null)},[filters,years,schools,setHeaderControls]);
 if(loading)return <section className="kitchen-rental-page"><div className="dashboard-empty-state">Loading Kitchen Rental data…</div></section>;if(loadError)return <section className="kitchen-rental-page"><div className="dashboard-empty-state">{loadError}</div></section>;if(!scopeRecords.length)return <section className="kitchen-rental-page"><div className="dashboard-empty-state">No Kitchen Rental records match the selected filters.</div></section>;
 const selectedYears=filters.academicYear?[filters.academicYear]:[...years].sort((a,b)=>a.localeCompare(b)),latestYear=filters.academicYear||years[0]||"",latestYearItems=scopeRecords.filter(item=>item.academicYear===latestYear),latest=combineRecords(latestYearItems),recognisedRevenue=filters.academicYear?recognisedForYear(latestYearItems,latestYear):scopeRecords.reduce((sum,item)=>sum+item.months.reduce((s,row)=>s+Number(row.revenue||0),0),0);
 const monthlyData=selectedYears.flatMap(year=>{const combined=combineRecords(scopeRecords.filter(item=>item.academicYear===year)),count=Math.min(reportingMonthCount(year),12);let cumulative=0;return MONTH_ORDER.map((label,index)=>{const row=combined.months.find(item=>item.month===label),revenue=index<count?Number(row?.revenue||0):0,raw=calendarMonthForAcademicYear(year,label);cumulative+=revenue;return{key:`${year}-${raw}`,academicYear:year,month:raw,label:displayMonth(raw),term:row?.term||(index<4?"Term 1":index<7?"Term 2":"Term 3"),revenue,cumulativeRevenue:cumulative}})});
 const currencyTooltip=<DashboardCurrencyTooltip formatValue={formatCurrency}/>,monthlyColumns=[{key:"academicYear",label:"Academic Year"},{key:"label",label:"Month"},{key:"term",label:"Term"},{key:"revenue",label:"Rental Revenue",numeric:true,tone:"sales",render:formatCurrency},{key:"cumulativeRevenue",label:"Cumulative Revenue",numeric:true,render:formatCurrency}],tableTotal=monthlyData.reduce((sum,item)=>sum+Number(item.revenue||0),0);
 return <section className="kitchen-rental-page">
  <section className="kitchen-rental-revenue-summary"><div className="kitchen-rental-revenue-copy"><span>Total Revenue</span><strong>{formatCurrency(recognisedRevenue)}</strong></div></section>
  <FixedRevenueComparison records={comparisonRecords(scopeRecords)} formatCurrency={formatCurrency} formatCompactCurrency={formatCompactCurrency} revenueLabel="Rental Revenue"/>
  <MonthlyTrendChart data={monthlyData} metrics={[{key:"revenue",label:"Monthly Revenue",tone:"secondary"},{key:"cumulativeRevenue",label:"Cumulative Revenue",tone:"primary"}]} defaultMetric="Monthly Revenue" formatAxis={formatCompactCurrency} tooltipContent={currencyTooltip} className="kitchen-rental-wide-card"/>
  <MonthlyResultsTable data={monthlyData} columns={monthlyColumns} totals={{revenue:formatCurrency(tableTotal),cumulativeRevenue:formatCurrency(tableTotal)}} emptyMessage="No Kitchen Rental records match the selected filters." resetKey={`${filters.academicYear}|${filters.school}`}/>
  <article className="kitchen-rental-terms-card"><div className="kitchen-rental-terms-heading"><div><span>Contracts</span><h2>Contract Overview</h2></div><span className="kitchen-rental-status">{latest.contracts.length} {latest.contracts.length===1?"contract":"contracts"}</span></div>{latest.contracts.length?<div className="kitchen-rental-contract-grid">{latest.contracts.map(contract=><div className="kitchen-rental-contract-card" key={`${contract.contractId}-${contract.schoolCode}`}><div className="kitchen-rental-contract-top"><div><strong>{contract.supplierName}</strong><div className="kitchen-rental-contract-school">{contract.school}</div></div></div><div className="kitchen-rental-contract-value"><strong>{formatCurrency(contract.annualAmount)}</strong><span>Annual Contract Value</span></div><div className="kitchen-rental-contract-period"><span>{formatDate(contract.startDate)}</span><i>→</i><span>{formatDate(contract.expiryDate)}</span></div></div>)}</div>:<div className="kitchen-rental-empty-contract">No contract information is available for {latestYear} and the selected school scope.</div>}</article>
 </section>
}
