import { useEffect,useMemo,useState } from "react";
import { useOutletContext } from "react-router-dom";
import { Bar,BarChart,CartesianGrid,Legend,Line,LineChart,ResponsiveContainer,Tooltip,XAxis,YAxis } from "recharts";
import { fetchCommercialOverviewRecords } from "../../lib/commercialOverviewData";
import { buildMonthlyReport,formatCompactCurrency,formatCurrency,formatPercent,previousAcademicYear,summariseMonthly,unique,variancePercent } from "../../lib/commercialReportingData";
import "./CommercialReportingPage.css";

function latestYear(years){return[...years].sort((a,b)=>b.localeCompare(a))[0]||""}
function DownloadIcon(){return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 3v12m0 0 4-4m-4 4-4-4M5 19h14"/></svg>}
function exportCsv(rows,meta){const headings=["Month","Actual",meta.comparisonScenario,"Variance","Variance %","Prior Year Actual","YoY %"],data=rows.map(row=>[row.monthLabel,row.actual,row.comparison,row.variance,row.variancePercent??"",row.priorYear,row.yoyPercent??""]);const lines=[["Commercial Reporting"],["Academic Year",meta.academicYear],["School",meta.school||"All Schools"],["Revenue Stream",meta.stream||"All Revenue Streams"],["Measure",meta.measure==="income"?"School Income / Commission":"Commercial Revenue"],["Comparison",meta.comparisonScenario],[],headings,...data].map(row=>row.map(value=>`"${String(value??"").replaceAll('"','""')}"`).join(","));const blob=new Blob(["\ufeff"+lines.join("\n")],{type:"text/csv;charset=utf-8"}),url=URL.createObjectURL(blob),anchor=document.createElement("a");anchor.href=url;anchor.download=`commercial-report-${meta.academicYear||"report"}.csv`;anchor.click();URL.revokeObjectURL(url)}

export default function CommercialReportingPage(){
 const{setHeaderControls}=useOutletContext();
 const[records,setRecords]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const[academicYear,setAcademicYear]=useState(""),[school,setSchool]=useState(""),[stream,setStream]=useState(""),[measure,setMeasure]=useState("revenue"),[comparisonScenario,setComparisonScenario]=useState("Forecast"),[comparisonMode,setComparisonMode]=useState("yoy");
 useEffect(()=>{let active=true;(async()=>{try{const data=await fetchCommercialOverviewRecords();if(!active)return;setRecords(data);setAcademicYear(latestYear(unique(data.map(row=>row.academicYear))))}catch(e){if(active)setError(e?.message||"Unable to load commercial reporting data.")}finally{if(active)setLoading(false)}})();return()=>{active=false}},[]);
 const years=useMemo(()=>unique(records.map(row=>row.academicYear)).sort((a,b)=>b.localeCompare(a)),[records]);
 const schools=useMemo(()=>unique(records.map(row=>row.schoolName||row.schoolCode)).sort(),[records]);
 const streams=useMemo(()=>{const map=new Map();records.forEach(row=>{if(row.streamCode)map.set(row.streamCode,row.streamName||row.streamCode)});return[...map.entries()].sort((a,b)=>a[1].localeCompare(b[1]))},[records]);
 useEffect(()=>{setHeaderControls(<div className="reporting-header-filters"><label><span>Academic Year</span><select value={academicYear} onChange={e=>setAcademicYear(e.target.value)}>{years.map(year=><option key={year}>{year}</option>)}</select></label><label><span>School</span><select value={school} onChange={e=>setSchool(e.target.value)}><option value="">All Schools</option>{schools.map(item=><option key={item}>{item}</option>)}</select></label></div>);return()=>setHeaderControls(null)},[academicYear,school,schools,setHeaderControls,years]);
 const scopedRecords=useMemo(()=>records.filter(row=>(!school||(row.schoolName||row.schoolCode)===school)&&(!stream||row.streamCode===stream)),[records,school,stream]);
 const monthlyRows=useMemo(()=>buildMonthlyReport(scopedRecords,{academicYear,measure,comparisonScenario}),[scopedRecords,academicYear,measure,comparisonScenario]);
 const totals=useMemo(()=>summariseMonthly(monthlyRows),[monthlyRows]),comparisonVariance=variancePercent(totals.actual,totals.comparison),yoyVariance=variancePercent(totals.actual,totals.priorYear);
 const comparisonRows=useMemo(()=>{if(comparisonMode==="mom")return monthlyRows.map((row,index)=>({...row,period:row.monthLabel,previous:index?monthlyRows[index-1].actual:0,growth:index?variancePercent(row.actual,monthlyRows[index-1].actual):null}));return monthlyRows.map(row=>({...row,period:row.monthLabel,previous:row.priorYear,growth:row.yoyPercent}))},[comparisonMode,monthlyRows]);
 if(loading)return <section className="commercial-reporting-page"><div className="reporting-empty">Loading Commercial Reporting…</div></section>;
 if(error)return <section className="commercial-reporting-page"><div className="reporting-empty">{error}</div></section>;
 return <section className="commercial-reporting-page">
  <div className="reporting-toolbar"><div className="reporting-filter-row"><label><span>Revenue Stream</span><select value={stream} onChange={e=>setStream(e.target.value)}><option value="">All Revenue Streams</option>{streams.map(([code,name])=><option key={code} value={code}>{name}</option>)}</select></label><label><span>Measure</span><select value={measure} onChange={e=>setMeasure(e.target.value)}><option value="revenue">Commercial Revenue</option><option value="income">School Income / Commission</option></select></label><label><span>Compare Actual To</span><select value={comparisonScenario} onChange={e=>setComparisonScenario(e.target.value)}><option>Forecast</option><option>Budget</option></select></label></div><button className="reporting-export-button" onClick={()=>exportCsv(monthlyRows,{academicYear,school,stream:streams.find(([code])=>code===stream)?.[1]||"",measure,comparisonScenario})}><DownloadIcon/>Export Report</button></div>
  <section className="reporting-kpi-grid"><article><span>Actual</span><strong>{formatCurrency(totals.actual)}</strong><small>{academicYear}</small></article><article><span>{comparisonScenario}</span><strong>{formatCurrency(totals.comparison)}</strong><small>Selected period</small></article><article><span>Variance vs {comparisonScenario}</span><strong className={comparisonVariance!==null&&comparisonVariance<0?"negative":"positive"}>{formatPercent(comparisonVariance)}</strong><small>{formatCurrency(totals.actual-totals.comparison)}</small></article><article><span>Year on Year</span><strong className={yoyVariance!==null&&yoyVariance<0?"negative":"positive"}>{formatPercent(yoyVariance)}</strong><small>vs {previousAcademicYear(academicYear)||"prior year"}</small></article></section>
  <article className="reporting-card"><div className="reporting-card-heading"><div><span>MONTHLY PERFORMANCE</span><h2>{measure==="income"?"School Income / Commission":"Commercial Revenue"}</h2><p>Actual performance against {comparisonScenario.toLowerCase()} and the prior academic year.</p></div></div><div className="reporting-table-scroll"><table className="reporting-table"><thead><tr><th>Month</th><th>Actual</th><th>{comparisonScenario}</th><th>Variance</th><th>Variance %</th><th>Prior Year</th><th>YoY %</th></tr></thead><tbody>{monthlyRows.map(row=><tr key={row.month}><th>{row.monthLabel}</th><td className="actual">{formatCurrency(row.actual)}</td><td>{formatCurrency(row.comparison)}</td><td>{formatCurrency(row.variance)}</td><td><span className={`variance-pill ${row.variancePercent===null?"neutral":row.variancePercent>=0?"positive":"negative"}`}>{formatPercent(row.variancePercent)}</span></td><td>{formatCurrency(row.priorYear)}</td><td><span className={`variance-pill ${row.yoyPercent===null?"neutral":row.yoyPercent>=0?"positive":"negative"}`}>{formatPercent(row.yoyPercent)}</span></td></tr>)}</tbody><tfoot><tr><th>Total</th><td>{formatCurrency(totals.actual)}</td><td>{formatCurrency(totals.comparison)}</td><td>{formatCurrency(totals.actual-totals.comparison)}</td><td>{formatPercent(comparisonVariance)}</td><td>{formatCurrency(totals.priorYear)}</td><td>{formatPercent(yoyVariance)}</td></tr></tfoot></table></div></article>
  <article className="reporting-card"><div className="reporting-card-heading reporting-heading-with-tabs"><div><span>PERFORMANCE COMPARISON</span><h2>{comparisonMode==="yoy"?"Year on Year":"Month on Month"}</h2><p>Monthly growth view for the selected reporting scope.</p></div><div className="reporting-segmented"><button className={comparisonMode==="yoy"?"active":""} onClick={()=>setComparisonMode("yoy")}>Year on Year</button><button className={comparisonMode==="mom"?"active":""} onClick={()=>setComparisonMode("mom")}>Month on Month</button></div></div><div className="reporting-comparison-grid"><div className="reporting-chart"><ResponsiveContainer width="100%" height="100%"><BarChart data={comparisonRows}><CartesianGrid strokeDasharray="3 5" vertical={false}/><XAxis dataKey="period"/><YAxis tickFormatter={formatCompactCurrency}/><Tooltip formatter={formatCurrency}/><Legend/><Bar dataKey="actual" name="Current" fill="#111827" radius={[4,4,0,0]}/><Bar dataKey="previous" name="Comparison" fill="#8b5cf6" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div><div className="reporting-growth-list">{comparisonRows.map(row=><div key={row.month}><span>{row.period}</span><strong>{formatPercent(row.growth)}</strong></div>)}</div></div></article>
  <article className="reporting-card"><div className="reporting-card-heading"><div><span>TREND & VARIANCE</span><h2>Actual vs {comparisonScenario}</h2><p>Monthly movement across the selected academic year.</p></div></div><div className="reporting-trend-chart"><ResponsiveContainer width="100%" height="100%"><LineChart data={monthlyRows}><CartesianGrid strokeDasharray="3 5" vertical={false}/><XAxis dataKey="monthLabel"/><YAxis tickFormatter={formatCompactCurrency}/><Tooltip formatter={formatCurrency}/><Legend/><Line type="monotone" dataKey="actual" name="Actual" stroke="#111827" strokeWidth={2.5}/><Line type="monotone" dataKey="comparison" name={comparisonScenario} stroke="#8b5cf6" strokeWidth={2.5}/></LineChart></ResponsiveContainer></div></article>
 </section>
}
