import { Fragment,useEffect,useMemo,useRef,useState } from "react";
function groupByAcademicYear(data){const grouped=new Map();data.forEach(item=>{const key=item.academicYear||"Other";if(!grouped.has(key))grouped.set(key,[]);grouped.get(key).push(item)});return[...grouped.entries()].sort(([a],[b])=>b.localeCompare(a)).map(([academicYear,rows])=>({academicYear,rows}))}
function getCellClass(column,extraClass=""){return[column.numeric?"dashboard-numeric-cell":"",column.tone?`dashboard-value-${column.tone}`:"",extraClass].filter(Boolean).join(" ")}
export default function MonthlyResultsTable({data=[],columns=[],totals={},totalLabel="Selected Total",emptyMessage="No records match the selected filters.",resetKey="",renderExpandedRow=null}){
 const[page,setPage]=useState(0),[expandedKey,setExpandedKey]=useState("");const tableRef=useRef(null),pages=useMemo(()=>groupByAcademicYear(data),[data]),safePage=Math.min(page,Math.max(pages.length-1,0)),current=pages[safePage];
 useEffect(()=>{setPage(0);setExpandedKey("")},[resetKey]);
 useEffect(()=>{if(!expandedKey)return;const onKey=e=>{if(e.key==="Escape")setExpandedKey("")};const onPointer=e=>{if(tableRef.current&&!tableRef.current.contains(e.target))setExpandedKey("")};document.addEventListener("keydown",onKey);document.addEventListener("pointerdown",onPointer);return()=>{document.removeEventListener("keydown",onKey);document.removeEventListener("pointerdown",onPointer)}},[expandedKey]);
 const totalEntries=Object.entries(totals),totalColSpan=Math.max(columns.length-totalEntries.length,1);
 return <section className="dashboard-table-card" ref={tableRef}><div className="dashboard-card-heading"><div><h2>Monthly Results</h2><p>Detailed monthly performance for the selected reporting scope.</p></div><span className="dashboard-record-count">{current?.academicYear?`${current.academicYear} · `:""}{current?.rows?.length||0} months</span></div>{!data.length?<div className="dashboard-empty-state">{emptyMessage}</div>:<div className="dashboard-table-scroll"><table className="dashboard-results-table"><thead><tr>{columns.map(column=><th key={column.key} className={getCellClass(column)}>{column.label}</th>)}</tr></thead><tbody>{(current?.rows||[]).map(item=>{const rowKey=item.key||`${item.academicYear}-${item.month}`,expanded=expandedKey===rowKey;return <Fragment key={rowKey}><tr>{columns.map(column=><td key={column.key} className={getCellClass(column)}>{column.render?column.render(item[column.key],item,{expanded,toggle:()=>setExpandedKey(expanded?"":rowKey)}):item[column.key]}</td>)}</tr>{expanded&&renderExpandedRow?<tr className="dashboard-expanded-detail-row"><td colSpan={columns.length}>{renderExpandedRow(item)}</td></tr>:null}</Fragment>})}</tbody><tfoot><tr><th colSpan={totalColSpan} className="dashboard-total-label">{totalLabel}</th>{totalEntries.map(([key,value])=>{const column=columns.find(item=>item.key===key)||{numeric:true};return <th key={key} className={getCellClass(column,"dashboard-total-value")}>{value}</th>})}</tr></tfoot></table></div>}{pages.length>1?<div className="dashboard-results-pagination"><button type="button" onClick={()=>setPage(currentPage=>Math.max(0,currentPage-1))} disabled={safePage===0}>‹</button><div className="dashboard-pagination-pages">{pages.map((item,index)=><button key={item.academicYear} type="button" className={safePage===index?"active":""} onClick={()=>setPage(index)} title={item.academicYear}>{index+1}</button>)}</div><button type="button" onClick={()=>setPage(currentPage=>Math.min(pages.length-1,currentPage+1))} disabled={safePage===pages.length-1}>›</button><span>{current?.academicYear}</span></div>:null}</section>
}
