import { useEffect, useMemo, useState } from "react";

import { useAuth } from "../../auth/AuthProvider";
import {
  archiveFinancialRecord,
  fetchDataEntryOptions,
  fetchFinancialRecords,
  getAcademicYearFromMonth,
  getFinanceTermFromMonth,
  restoreFinancialRecord,
  saveFinancialRecords,
  updateFinancialRecord,
} from "../../lib/financialData";
import "./DataEntryPage.css";

const SCENARIOS = ["Actual", "Budget", "Forecast"];
const PAGE_SIZE = 25;
const MONTHS = [["01","January"],["02","February"],["03","March"],["04","April"],["05","May"],["06","June"],["07","July"],["08","August"],["09","September"],["10","October"],["11","November"],["12","December"]].map(([value,label])=>({value,label}));
const metricKey=(m)=>String(m?.code||m?.name||"").trim().toLowerCase();
const metricLabel=(m)=>m?.name||m?.code||"Metric";
function uniqueMetrics(metrics=[]){const seen=new Set();return metrics.filter(m=>{const k=metricKey(m);if(!k||seen.has(k))return false;seen.add(k);return true;});}
function getYearOptions(){const y=new Date().getFullYear();return Array.from({length:12},(_,i)=>String(y+3-i));}
function combineMonthYear(y,m){return y&&m?`${y}-${m}`:"";}
function formatRecordMonth(v){if(!v)return"—";return new Intl.DateTimeFormat("en-GB",{month:"short",year:"numeric"}).format(new Date(`${v}T00:00:00`));}
function formatMoney(v){return new Intl.NumberFormat("en-AE",{style:"currency",currency:"AED",maximumFractionDigits:2}).format(Number(v||0));}
function buildPaginationItems(c,t){if(t<=7)return Array.from({length:t},(_,i)=>i+1);const a=[1],s=Math.max(2,c-1),e=Math.min(t-1,c+1);if(s>2)a.push("start-ellipsis");for(let p=s;p<=e;p++)a.push(p);if(e<t-1)a.push("end-ellipsis");a.push(t);return a;}

export default function DataEntryPage(){
 const {role}=useAuth(); const canEdit=role==="admin"||role==="editor",canRestore=role==="admin";
 const [mode,setMode]=useState("new"),[options,setOptions]=useState({schools:[],revenueStreams:[],metrics:[]}),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[success,setSuccess]=useState("");
 const [form,setForm]=useState({schoolId:"",revenueStreamId:"",reportingMonth:"",reportingYear:String(new Date().getFullYear()),scenario:"Actual"}),[metricValues,setMetricValues]=useState({});
 const [records,setRecords]=useState([]),[recordsLoading,setRecordsLoading]=useState(false),[recordsError,setRecordsError]=useState("");
 const [recordFilters,setRecordFilters]=useState({schoolId:"",revenueStreamId:"",metricCode:"",academicYear:"",scenario:"",search:"",includeDeleted:false});
 const [currentPage,setCurrentPage]=useState(1),[editingRecord,setEditingRecord]=useState(null),[editAmount,setEditAmount]=useState(""),[recordActionLoading,setRecordActionLoading]=useState(false),[deleteRecord,setDeleteRecord]=useState(null);
 const yearOptions=useMemo(getYearOptions,[]);
 useEffect(()=>{let active=true;(async()=>{try{setLoading(true);const d=await fetchDataEntryOptions();if(active)setOptions(d);}catch(e){if(active)setError(e?.message||"Unable to load the financial records workspace.");}finally{if(active)setLoading(false);}})();return()=>{active=false;};},[]);
 const selectedSchool=useMemo(()=>options.schools.find(s=>String(s.id)===String(form.schoolId)),[options.schools,form.schoolId]);
 const selectedStream=useMemo(()=>options.revenueStreams.find(s=>String(s.id)===String(form.revenueStreamId)),[options.revenueStreams,form.revenueStreamId]);
 const streamMetrics=useMemo(()=>options.metrics.filter(m=>String(m.revenue_stream_id)===String(form.revenueStreamId)),[options.metrics,form.revenueStreamId]);
 const managementMetrics=useMemo(()=>{const source=recordFilters.revenueStreamId?options.metrics.filter(m=>String(m.revenue_stream_id)===String(recordFilters.revenueStreamId)):options.metrics;return uniqueMetrics(source).sort((a,b)=>metricLabel(a).localeCompare(metricLabel(b)));},[options.metrics,recordFilters.revenueStreamId]);
 const combinedMonth=combineMonthYear(form.reportingYear,form.reportingMonth),academicYear=getAcademicYearFromMonth(combinedMonth),term=getFinanceTermFromMonth(combinedMonth);
 const availableAcademicYears=useMemo(()=>[...new Set(records.map(r=>r.academic_year).filter(Boolean))].sort((a,b)=>b.localeCompare(a)),[records]);
 const visibleRecords=useMemo(()=>{const q=recordFilters.search.trim().toLowerCase();return records.filter(r=>{if(!recordFilters.includeDeleted&&r.is_deleted)return false;if(recordFilters.schoolId&&String(r.school?.id)!==String(recordFilters.schoolId))return false;if(recordFilters.revenueStreamId&&String(r.revenue_stream?.id)!==String(recordFilters.revenueStreamId))return false;if(recordFilters.metricCode&&metricKey(r.metric)!==recordFilters.metricCode)return false;if(recordFilters.academicYear&&r.academic_year!==recordFilters.academicYear)return false;if(recordFilters.scenario&&r.scenario!==recordFilters.scenario)return false;if(q){const h=[r.school?.name,r.school?.code,r.revenue_stream?.name,r.metric?.name,r.metric?.code,r.academic_year,r.term,r.scenario].filter(Boolean).join(" ").toLowerCase();if(!h.includes(q))return false;}return true;});},[records,recordFilters]);
 const totalPages=Math.max(1,Math.ceil(visibleRecords.length/PAGE_SIZE)),paginatedRecords=useMemo(()=>visibleRecords.slice((currentPage-1)*PAGE_SIZE,currentPage*PAGE_SIZE),[visibleRecords,currentPage]),paginationItems=useMemo(()=>buildPaginationItems(currentPage,totalPages),[currentPage,totalPages]),pageStart=visibleRecords.length?(currentPage-1)*PAGE_SIZE+1:0,pageEnd=Math.min(currentPage*PAGE_SIZE,visibleRecords.length);
 useEffect(()=>setCurrentPage(1),[recordFilters]); useEffect(()=>{if(currentPage>totalPages)setCurrentPage(totalPages);},[currentPage,totalPages]);
 async function loadRecords(){try{setRecordsLoading(true);setRecordsError("");setRecords(await fetchFinancialRecords({includeDeleted:recordFilters.includeDeleted}));}catch(e){setRecordsError(e?.message||"Unable to load financial records.");}finally{setRecordsLoading(false);}}
 useEffect(()=>{if(mode==="manage")loadRecords();},[mode,recordFilters.includeDeleted]);
 function updateForm(n,v){setSuccess("");setError("");setForm(c=>({...c,[n]:v}));if(n==="revenueStreamId")setMetricValues({});}
 function updateRecordFilter(n,v){setRecordFilters(c=>{const x={...c,[n]:v};if(n==="revenueStreamId")x.metricCode="";return x;});}
 function updateMetric(id,v){setMetricValues(c=>({...c,[id]:v}));}
 function resetForm(){setForm({schoolId:"",revenueStreamId:"",reportingMonth:"",reportingYear:String(new Date().getFullYear()),scenario:"Actual"});setMetricValues({});setSuccess("");setError("");}
 async function handleSubmit(e){e.preventDefault();if(!canEdit)return setError("Your account does not have permission to modify financial records.");if(!form.schoolId||!form.revenueStreamId||!form.reportingMonth||!form.reportingYear)return setError("Select a school, revenue stream, reporting month and year.");try{setSaving(true);setError("");setSuccess("");const r=await saveFinancialRecords({schoolId:form.schoolId,revenueStreamId:form.revenueStreamId,month:combinedMonth,scenario:form.scenario,metricValues});setSuccess(`${r.savedCount} ${r.savedCount===1?"record":"records"} saved successfully.`);}catch(e){setError(e?.message||"Unable to save the financial records.");}finally{setSaving(false);}}
 function openEdit(r){setEditingRecord(r);setEditAmount(String(r.amount??""));}
 async function saveEdit(){if(!editingRecord||!canEdit)return;try{setRecordActionLoading(true);await updateFinancialRecord(editingRecord.id,{amount:editAmount});setEditingRecord(null);await loadRecords();}catch(e){setRecordsError(e?.message||"Unable to update the financial record.");}finally{setRecordActionLoading(false);}}
 async function confirmArchive(){if(!deleteRecord||!canEdit)return;try{setRecordActionLoading(true);await archiveFinancialRecord(deleteRecord.id);setDeleteRecord(null);await loadRecords();}catch(e){setRecordsError(e?.message||"Unable to archive the financial record.");}finally{setRecordActionLoading(false);}}
 async function handleRestore(r){if(!canRestore)return;try{setRecordActionLoading(true);await restoreFinancialRecord(r.id);await loadRecords();}catch(e){setRecordsError(e?.message||"Unable to restore the financial record.");}finally{setRecordActionLoading(false);}}
 if(loading)return <section className="data-entry-page"><div className="data-entry-loading">Loading Financial Records…</div></section>;
 return <section className="data-entry-page">
  <div className="data-entry-intro"><div><span className="data-entry-eyebrow">FINANCIAL RECORDS</span><h2>Commercial Data Workspace</h2><p>Create, review and maintain monthly financial performance across schools and revenue streams.</p></div><div className="data-entry-status"><span className="status-dot"/>Supabase connected</div></div>
  <div className="records-mode-switch"><button type="button" className={mode==="new"?"active":""} onClick={()=>setMode("new")}>＋ New Record</button><button type="button" className={mode==="manage"?"active":""} onClick={()=>setMode("manage")}>≡ Manage Records</button></div>
  {!canEdit&&<div className="data-entry-permission-banner">You currently have read-only access.</div>}
  {mode==="new"?<form className="data-entry-workspace" onSubmit={handleSubmit}><section className="data-entry-main-card"><div className="entry-card-header"><div><span className="entry-step">RECORD DETAILS</span><h3>Monthly Financial Record</h3><p>Select the school, revenue stream and reporting period.</p></div></div><div className="entry-fields-grid">
   <label className="entry-field"><span>School</span><select value={form.schoolId} onChange={e=>updateForm("schoolId",e.target.value)}><option value="">Select school</option>{options.schools.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>
   <label className="entry-field"><span>Revenue Stream</span><select value={form.revenueStreamId} onChange={e=>updateForm("revenueStreamId",e.target.value)}><option value="">Select revenue stream</option>{options.revenueStreams.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>
   <div className="reporting-period-group"><label className="entry-field"><span>Month</span><select value={form.reportingMonth} onChange={e=>updateForm("reportingMonth",e.target.value)}><option value="">Select month</option>{MONTHS.map(m=><option key={m.value} value={m.value}>{m.label}</option>)}</select></label><label className="entry-field"><span>Year</span><select value={form.reportingYear} onChange={e=>updateForm("reportingYear",e.target.value)}>{yearOptions.map(y=><option key={y}>{y}</option>)}</select></label></div>
   <label className="entry-field"><span>Scenario</span><select value={form.scenario} onChange={e=>updateForm("scenario",e.target.value)}>{SCENARIOS.map(s=><option key={s}>{s}</option>)}</select></label></div>
   <div className="period-preview"><div><span>Academic Year</span><strong>{academicYear||"—"}</strong></div><div className="period-divider"/><div><span>Finance Term</span><strong>{term||"—"}</strong></div><div className="period-divider"/><div><span>Basis</span><strong>Sep – Aug</strong></div></div>
   <div className="metrics-section"><div className="metrics-heading"><div><span className="entry-step">VALUES</span><h3>Financial Metrics</h3></div>{selectedStream&&<span className="selected-stream-pill">{selectedStream.name}</span>}</div>{!form.revenueStreamId?<div className="metric-placeholder"><strong>Select a revenue stream</strong></div>:<div className="metric-input-grid">{streamMetrics.map(m=><label className="metric-entry-card" key={m.id}><span>{metricLabel(m)}</span><div className="money-input"><span>AED</span><input type="number" min="0" step="0.01" value={metricValues[m.id]??""} onChange={e=>updateMetric(m.id,e.target.value)}/></div></label>)}</div>}</div></section>
   <aside className="data-entry-review-card"><div className="review-header"><span className="entry-step">REVIEW</span><h3>Record Summary</h3></div><div className="review-list"><div><span>School</span><strong>{selectedSchool?.name||"—"}</strong></div><div><span>Revenue Stream</span><strong>{selectedStream?.name||"—"}</strong></div><div><span>Academic Year</span><strong>{academicYear||"—"}</strong></div><div><span>Term</span><strong>{term||"—"}</strong></div><div><span>Scenario</span><strong>{form.scenario}</strong></div></div>{error&&<div className="entry-message error">{error}</div>}{success&&<div className="entry-message success">{success}</div>}<div className="entry-actions"><button type="button" className="entry-reset-button" onClick={resetForm}>Reset</button><button type="submit" className="entry-save-button" disabled={saving||!canEdit}>{saving?"Saving…":"Save Records"}</button></div></aside></form>
  :<section className="manage-records-card"><div className="manage-records-header"><div><span className="entry-step">RECORD LIBRARY</span><h3>Manage Financial Records</h3></div><div className="record-count-badge">{visibleRecords.length} records</div></div><div className="record-filter-grid">
   <label className="entry-field search-field"><span>Search</span><input type="search" placeholder="School, stream, metric…" value={recordFilters.search} onChange={e=>updateRecordFilter("search",e.target.value)}/></label>
   <label className="entry-field"><span>School</span><select value={recordFilters.schoolId} onChange={e=>updateRecordFilter("schoolId",e.target.value)}><option value="">All Schools</option>{options.schools.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>
   <label className="entry-field"><span>Revenue Stream</span><select value={recordFilters.revenueStreamId} onChange={e=>updateRecordFilter("revenueStreamId",e.target.value)}><option value="">All Streams</option>{options.revenueStreams.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>
   <label className="entry-field"><span>Metric</span><select value={recordFilters.metricCode} onChange={e=>updateRecordFilter("metricCode",e.target.value)}><option value="">All Metrics</option>{managementMetrics.map(m=><option key={metricKey(m)} value={metricKey(m)}>{metricLabel(m)}</option>)}</select></label>
   <label className="entry-field"><span>Academic Year</span><select value={recordFilters.academicYear} onChange={e=>updateRecordFilter("academicYear",e.target.value)}><option value="">All Years</option>{availableAcademicYears.map(y=><option key={y}>{y}</option>)}</select></label>
   <label className="entry-field"><span>Scenario</span><select value={recordFilters.scenario} onChange={e=>updateRecordFilter("scenario",e.target.value)}><option value="">All Scenarios</option>{SCENARIOS.map(s=><option key={s}>{s}</option>)}</select></label><label className="archive-toggle"><input type="checkbox" checked={recordFilters.includeDeleted} onChange={e=>updateRecordFilter("includeDeleted",e.target.checked)}/><span>Show archived</span></label></div>
   {recordsError&&<div className="entry-message error manage-message">{recordsError}</div>}{recordsLoading?<div className="records-loading">Loading records…</div>:visibleRecords.length===0?<div className="records-empty"><strong>No records found</strong></div>:<><div className="records-table-wrap"><table className="records-table"><thead><tr><th>Period</th><th>School</th><th>Revenue Stream</th><th>Metric</th><th>Scenario</th><th>Amount</th><th>Status</th><th/></tr></thead><tbody>{paginatedRecords.map(r=><tr key={r.id} className={r.is_deleted?"archived-row":""}><td><strong>{formatRecordMonth(r.month)}</strong><span>{r.academic_year}</span></td><td><strong>{r.school?.name||"—"}</strong><span>{r.school?.code||""}</span></td><td>{r.revenue_stream?.name||"—"}</td><td>{metricLabel(r.metric)}</td><td><span className={`scenario-pill ${String(r.scenario||"").toLowerCase()}`}>{r.scenario||"—"}</span></td><td className="record-amount">{formatMoney(r.amount)}</td><td><span className={`record-status ${r.is_deleted?"archived":"active"}`}>{r.is_deleted?"Archived":"Active"}</span></td><td className="record-actions-cell">{r.is_deleted?canRestore&&<button className="record-action restore" onClick={()=>handleRestore(r)}>Restore</button>:<div className="record-actions"><button className="record-action" onClick={()=>openEdit(r)}>Edit</button><button className="record-action danger" onClick={()=>setDeleteRecord(r)}>Archive</button></div>}</td></tr>)}</tbody></table></div><div className="records-pagination"><div className="pagination-summary">Showing <strong>{pageStart}–{pageEnd}</strong> of <strong>{visibleRecords.length}</strong> records</div><div className="pagination-controls"><button className="pagination-arrow" onClick={()=>setCurrentPage(p=>Math.max(1,p-1))} disabled={currentPage===1}>‹</button>{paginationItems.map(i=>typeof i==="number"?<button key={i} className={`pagination-page ${currentPage===i?"active":""}`} onClick={()=>setCurrentPage(i)}>{i}</button>:<span key={i}>…</span>)}<button className="pagination-arrow" onClick={()=>setCurrentPage(p=>Math.min(totalPages,p+1))} disabled={currentPage===totalPages}>›</button></div></div></>}</section>}
  {editingRecord&&<div className="record-modal-backdrop"><div className="record-modal edit-record-modal"><div className="record-modal-header"><div><span className="entry-step">EDIT RECORD</span><h3>{metricLabel(editingRecord.metric)}</h3><p>Change the amount for this existing record. Its reporting period and classification remain fixed.</p></div><button className="modal-close" onClick={()=>setEditingRecord(null)}>×</button></div><div className="edit-record-context"><div><span>School</span><strong>{editingRecord.school?.name}</strong></div><div><span>Revenue Stream</span><strong>{editingRecord.revenue_stream?.name}</strong></div><div><span>Metric</span><strong>{metricLabel(editingRecord.metric)}</strong></div><div><span>Period</span><strong>{formatRecordMonth(editingRecord.month)}</strong></div><div><span>Academic Year</span><strong>{editingRecord.academic_year}</strong></div><div><span>Scenario</span><strong>{editingRecord.scenario}</strong></div></div><label className="entry-field edit-amount-field"><span>Amount</span><div className="edit-money-input"><span className="edit-currency">AED</span><input type="text" inputMode="decimal" value={editAmount} onChange={e=>setEditAmount(e.target.value)} autoFocus/></div></label><div className="record-modal-actions"><button className="entry-reset-button" onClick={()=>setEditingRecord(null)}>Cancel</button><button className="entry-save-button" onClick={saveEdit} disabled={recordActionLoading||editAmount===""}>{recordActionLoading?"Saving…":"Save Amount"}</button></div></div></div>}
  {deleteRecord&&<div className="record-modal-backdrop"><div className="record-modal delete-modal"><div className="delete-icon">!</div><h3>Archive financial record?</h3><p>This record will disappear from normal dashboards but remain in the audit history and can be restored later.</p><div className="delete-record-summary"><strong>{deleteRecord.school?.name}</strong><span>{deleteRecord.revenue_stream?.name} · {metricLabel(deleteRecord.metric)}</span><span>{formatRecordMonth(deleteRecord.month)} · {deleteRecord.scenario}</span><b>{formatMoney(deleteRecord.amount)}</b></div><div className="record-modal-actions"><button className="entry-reset-button" onClick={()=>setDeleteRecord(null)}>Cancel</button><button className="archive-confirm-button" onClick={confirmArchive} disabled={recordActionLoading}>{recordActionLoading?"Archiving…":"Archive Record"}</button></div></div></div>}
 </section>;
}
