import { useEffect, useMemo, useState } from "react";
import { useAuth } from "../../auth/AuthProvider";
import { archiveFinancialRecord, fetchDataEntryOptions, fetchFinancialRecordAcademicYears, fetchFinancialRecords, getAcademicYearFromMonth, getFinanceTermFromMonth, restoreFinancialRecord, saveFinancialRecords, updateFinancialRecord } from "../../lib/financialData";
import { DEFAULT_VAT_RATE, VAT_BASES } from "../../lib/vat";
import "./DataEntryPage.css";

const SCENARIOS=["Actual","Budget","Forecast"],PAGE_SIZE=25;
const MONTHS=[["01","January"],["02","February"],["03","March"],["04","April"],["05","May"],["06","June"],["07","July"],["08","August"],["09","September"],["10","October"],["11","November"],["12","December"]].map(([value,label])=>({value,label}));
const VAT_OPTIONS=[{value:VAT_BASES.EXCLUSIVE,label:"VAT Exclusive"},{value:VAT_BASES.INCLUSIVE,label:"VAT Inclusive"},{value:VAT_BASES.NO_VAT,label:"No VAT / N/A"}];
const metricKey=m=>String(m?.code||m?.name||"").trim().toLowerCase(),metricLabel=m=>m?.name||m?.code||"Metric",isPercentageMetric=m=>metricKey(m)==="vat_rate"||metricLabel(m).trim().toLowerCase()==="vat rate",metricUnit=m=>isPercentageMetric(m)?"%":"AED";
function uniqueMetrics(a=[]){const s=new Set();return a.filter(m=>{const k=metricKey(m);if(!k||s.has(k))return false;s.add(k);return true;});}
function getYearOptions(){const y=new Date().getFullYear();return Array.from({length:12},(_,i)=>String(y+3-i));}
function formatRecordMonth(v){if(!v)return"—";return new Intl.DateTimeFormat("en-GB",{month:"short",year:"numeric"}).format(new Date(`${v}T00:00:00`));}
function formatMoney(v){return new Intl.NumberFormat("en-AE",{style:"currency",currency:"AED",maximumFractionDigits:2}).format(Number(v||0));}
function formatMetricValue(v,m){return isPercentageMetric(m)?`${Number(v||0).toLocaleString("en-AE",{maximumFractionDigits:2})}%`:formatMoney(v);}
function vatLabel(basis,rate){if(!basis)return"Unclassified";if(basis===VAT_BASES.NO_VAT)return"No VAT";return `${basis===VAT_BASES.INCLUSIVE?"Incl.":"Excl."} VAT · ${Number(rate??DEFAULT_VAT_RATE)}%`;}
function pages(c,t){if(t<=7)return Array.from({length:t},(_,i)=>i+1);const a=[1],s=Math.max(2,c-1),e=Math.min(t-1,c+1);if(s>2)a.push("s");for(let p=s;p<=e;p++)a.push(p);if(e<t-1)a.push("e");a.push(t);return a;}
function academicYearMonths(ay){if(!ay)return[];const match=String(ay).match(/AY(\d{4})-(\d{2})/);if(!match)return[];const start=Number(match[1]);return [[9,"September",start],[10,"October",start],[11,"November",start],[12,"December",start],[1,"January",start+1],[2,"February",start+1],[3,"March",start+1],[4,"April",start+1],[5,"May",start+1],[6,"June",start+1],[7,"July",start+1],[8,"August",start+1]].map(([m,label,y])=>({value:`${y}-${String(m).padStart(2,"0")}`,label:`${label} ${y}`}));}

export default function DataEntryPage(){
 const {role}=useAuth(),canEdit=role==="admin"||role==="editor",canRestore=role==="admin";
 const fresh=()=>({schoolId:"",revenueStreamId:"",programmeId:"",reportingMonth:"",reportingYear:String(new Date().getFullYear()),scenario:"Actual",vatBasis:VAT_BASES.EXCLUSIVE,vatRate:String(DEFAULT_VAT_RATE)});
 const [mode,setMode]=useState("new"),[options,setOptions]=useState({schools:[],revenueStreams:[],metrics:[],programmes:[]}),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(""),[success,setSuccess]=useState(""),[form,setForm]=useState(fresh),[metricValues,setMetricValues]=useState({});
 const [records,setRecords]=useState([]),[recordsLoading,setRecordsLoading]=useState(false),[recordsError,setRecordsError]=useState(""),[totalCount,setTotalCount]=useState(0),[availableAcademicYears,setAvailableAcademicYears]=useState([]);
 const [recordFilters,setRecordFilters]=useState({schoolId:"",revenueStreamId:"",metricCode:"",academicYear:"",month:"",scenario:"",category:"",programmeId:"",search:"",includeDeleted:false}),[currentPage,setCurrentPage]=useState(1),[editingRecord,setEditingRecord]=useState(null),[editAmount,setEditAmount]=useState(""),[editVatBasis,setEditVatBasis]=useState(""),[editVatRate,setEditVatRate]=useState(String(DEFAULT_VAT_RATE)),[recordActionLoading,setRecordActionLoading]=useState(false),[deleteRecord,setDeleteRecord]=useState(null);
 const yearOptions=useMemo(getYearOptions,[]);
 useEffect(()=>{let active=true;(async()=>{try{setLoading(true);const [d,years]=await Promise.all([fetchDataEntryOptions(),fetchFinancialRecordAcademicYears()]);if(active){setOptions(d);setAvailableAcademicYears(years);}}catch(e){if(active)setError(e?.message||"Unable to load the financial records workspace.");}finally{if(active)setLoading(false);}})();return()=>{active=false;};},[]);
 const selectedSchool=options.schools.find(s=>String(s.id)===String(form.schoolId)),selectedStream=options.revenueStreams.find(s=>String(s.id)===String(form.revenueStreamId)),selectedProgramme=options.programmes.find(p=>String(p.id)===String(form.programmeId)),isLeasing=selectedStream?.code==="leasing",streamMetrics=options.metrics.filter(m=>String(m.revenue_stream_id)===String(form.revenueStreamId));
 const managementStream=options.revenueStreams.find(s=>String(s.id)===String(recordFilters.revenueStreamId)),showManagementProgramme=managementStream?.code==="leasing";
 const managementMetrics=useMemo(()=>uniqueMetrics(recordFilters.revenueStreamId?options.metrics.filter(m=>String(m.revenue_stream_id)===String(recordFilters.revenueStreamId)):options.metrics).sort((a,b)=>metricLabel(a).localeCompare(metricLabel(b))),[options.metrics,recordFilters.revenueStreamId]);
 const leasingCategories=useMemo(()=>[...new Set(options.programmes.map(p=>p.category).filter(Boolean))].sort(),[options.programmes]);
 const leasingProgrammes=useMemo(()=>options.programmes.filter(p=>!recordFilters.category||p.category===recordFilters.category),[options.programmes,recordFilters.category]);
 const monthOptions=useMemo(()=>academicYearMonths(recordFilters.academicYear),[recordFilters.academicYear]);
 const combinedMonth=form.reportingYear&&form.reportingMonth?`${form.reportingYear}-${form.reportingMonth}`:"",academicYear=getAcademicYearFromMonth(combinedMonth),term=getFinanceTermFromMonth(combinedMonth);
 const selectedMetricIds=useMemo(()=>recordFilters.metricCode?options.metrics.filter(m=>metricKey(m)===recordFilters.metricCode&&(!recordFilters.revenueStreamId||String(m.revenue_stream_id)===String(recordFilters.revenueStreamId))).map(m=>m.id):[],[options.metrics,recordFilters.metricCode,recordFilters.revenueStreamId]);
 const categoryProgrammeIds=useMemo(()=>showManagementProgramme&&recordFilters.category&&!recordFilters.programmeId?options.programmes.filter(p=>p.category===recordFilters.category).map(p=>p.id):[],[showManagementProgramme,recordFilters.category,recordFilters.programmeId,options.programmes]);
 const searchResults=useMemo(()=>{const q=recordFilters.search.trim().toLowerCase();if(!q)return records;return records.filter(r=>[r.school?.name,r.school?.code,r.programme?.name,r.programme?.provider_name,r.revenue_stream?.name,r.metric?.name,r.academic_year,r.term,r.scenario,r.vat_basis].filter(Boolean).join(" ").toLowerCase().includes(q));},[records,recordFilters.search]);
 const usingSearch=Boolean(recordFilters.search.trim()),displayRecords=usingSearch?searchResults.slice((currentPage-1)*PAGE_SIZE,currentPage*PAGE_SIZE):records,displayCount=usingSearch?searchResults.length:totalCount,totalPages=Math.max(1,Math.ceil(displayCount/PAGE_SIZE)),paginationItems=pages(currentPage,totalPages),pageStart=displayCount?(currentPage-1)*PAGE_SIZE+1:0,pageEnd=Math.min(currentPage*PAGE_SIZE,displayCount);
 async function loadRecords(){try{setRecordsLoading(true);setRecordsError("");const result=await fetchFinancialRecords({schoolId:recordFilters.schoolId,revenueStreamId:recordFilters.revenueStreamId,academicYear:recordFilters.academicYear,month:recordFilters.month,scenario:recordFilters.scenario,metricIds:selectedMetricIds,programmeId:showManagementProgramme?recordFilters.programmeId:"",programmeIds:categoryProgrammeIds,includeDeleted:recordFilters.includeDeleted,page:currentPage,pageSize:PAGE_SIZE,fetchAll:usingSearch});setRecords(result.records);setTotalCount(result.totalCount);}catch(e){setRecordsError(e?.message||"Unable to load financial records.");}finally{setRecordsLoading(false);}}
 useEffect(()=>{if(mode==="manage")loadRecords();},[mode,currentPage,recordFilters.schoolId,recordFilters.revenueStreamId,recordFilters.metricCode,recordFilters.academicYear,recordFilters.month,recordFilters.scenario,recordFilters.category,recordFilters.programmeId,recordFilters.includeDeleted,recordFilters.search]);
 function updateForm(n,v){setSuccess("");setError("");setForm(c=>({...c,[n]:v,...(n==="revenueStreamId"?{programmeId:""}:{}),...(n==="vatBasis"&&v===VAT_BASES.NO_VAT?{vatRate:"0"}:{})}));if(n==="revenueStreamId")setMetricValues({});}
 function filter(n,v){setCurrentPage(1);setRecordFilters(c=>({...c,[n]:v,...(n==="revenueStreamId"?{metricCode:"",category:"",programmeId:""}:{}),...(n==="academicYear"?{month:""}:{}),...(n==="category"?{programmeId:""}:{})}));}
 function reset(){setForm(fresh());setMetricValues({});setSuccess("");setError("");}
 async function submit(e){e.preventDefault();if(!canEdit)return setError("Your account does not have permission to modify financial records.");if(!form.schoolId||!form.revenueStreamId||!form.reportingMonth||!form.reportingYear)return setError("Select a school, revenue stream, reporting month and year.");if(isLeasing&&!form.programmeId)return setError("Select a programme for Leasing financial records.");try{setSaving(true);setError("");setSuccess("");const r=await saveFinancialRecords({schoolId:form.schoolId,revenueStreamId:form.revenueStreamId,programmeId:form.programmeId,month:combinedMonth,scenario:form.scenario,metricValues,vatBasis:form.vatBasis,vatRate:form.vatRate});setSuccess(`${r.savedCount} ${r.savedCount===1?"record":"records"} saved successfully.`);}catch(e){setError(e?.message||"Unable to save the financial records.");}finally{setSaving(false);}}
 function openEdit(r){setEditingRecord(r);setEditAmount(String(r.amount??""));setEditVatBasis(r.vat_basis||"");setEditVatRate(String(r.vat_rate??DEFAULT_VAT_RATE));}
 async function saveEdit(){try{setRecordActionLoading(true);await updateFinancialRecord(editingRecord.id,{amount:editAmount,vatBasis:editVatBasis,vatRate:editVatRate});setEditingRecord(null);await loadRecords();}catch(e){setRecordsError(e?.message||"Unable to update the financial record.");}finally{setRecordActionLoading(false);}}
 async function archive(){try{setRecordActionLoading(true);await archiveFinancialRecord(deleteRecord.id);setDeleteRecord(null);await loadRecords();}catch(e){setRecordsError(e?.message||"Unable to archive the financial record.");}finally{setRecordActionLoading(false);}}
 async function restore(r){try{setRecordActionLoading(true);await restoreFinancialRecord(r.id);await loadRecords();}catch(e){setRecordsError(e?.message||"Unable to restore the financial record.");}finally{setRecordActionLoading(false);}}
 if(loading)return <section className="data-entry-page"><div className="data-entry-loading">Loading Financial Records…</div></section>;
 return <section className="data-entry-page">
  <div className="data-entry-intro"><div><span className="data-entry-eyebrow">FINANCIAL RECORDS</span><h2>Commercial Data Workspace</h2><p>Create, review and maintain monthly financial performance across schools and revenue streams.</p></div><div className="data-entry-status"><span className="status-dot"/>Supabase connected</div></div>
  <div className="records-mode-switch"><button type="button" className={mode==="new"?"active":""} onClick={()=>setMode("new")}>＋ New Record</button><button type="button" className={mode==="manage"?"active":""} onClick={()=>setMode("manage")}>≡ Manage Records</button></div>{!canEdit&&<div className="data-entry-permission-banner">You currently have read-only access.</div>}
  {mode==="new"?<form className="data-entry-workspace" onSubmit={submit}><section className="data-entry-main-card"><div className="entry-card-header"><div><span className="entry-step">RECORD DETAILS</span><h3>Monthly Financial Record</h3><p>Select the school, revenue stream and reporting period.</p></div></div><div className="entry-fields-grid">
   <label className="entry-field"><span>School</span><select value={form.schoolId} onChange={e=>updateForm("schoolId",e.target.value)}><option value="">Select school</option>{options.schools.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>
   <label className="entry-field"><span>Revenue Stream</span><select value={form.revenueStreamId} onChange={e=>updateForm("revenueStreamId",e.target.value)}><option value="">Select revenue stream</option>{options.revenueStreams.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label>
   {isLeasing&&<label className="entry-field"><span>Programme</span><select value={form.programmeId} onChange={e=>updateForm("programmeId",e.target.value)}><option value="">Select programme</option>{options.programmes.map(p=><option key={p.id} value={p.id}>{p.name}{p.provider_name?` — ${p.provider_name}`:""}</option>)}</select></label>}
   <div className="reporting-period-group"><label className="entry-field"><span>Month</span><select value={form.reportingMonth} onChange={e=>updateForm("reportingMonth",e.target.value)}><option value="">Select month</option>{MONTHS.map(m=><option key={m.value} value={m.value}>{m.label}</option>)}</select></label><label className="entry-field"><span>Year</span><select value={form.reportingYear} onChange={e=>updateForm("reportingYear",e.target.value)}>{yearOptions.map(y=><option key={y}>{y}</option>)}</select></label></div>
   <label className="entry-field"><span>Scenario</span><select value={form.scenario} onChange={e=>updateForm("scenario",e.target.value)}>{SCENARIOS.map(s=><option key={s}>{s}</option>)}</select></label>
   <label className="entry-field"><span>Entered Amount VAT Basis</span><select value={form.vatBasis} onChange={e=>updateForm("vatBasis",e.target.value)}>{VAT_OPTIONS.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></label>
   <label className="entry-field"><span>VAT Rate (%)</span><input type="number" min="0" max="100" step="0.01" value={form.vatRate} disabled={form.vatBasis===VAT_BASES.NO_VAT} onChange={e=>updateForm("vatRate",e.target.value)}/></label>
  </div><div className="period-preview"><div><span>Academic Year</span><strong>{academicYear||"—"}</strong></div><div className="period-divider"/><div><span>Finance Term</span><strong>{term||"—"}</strong></div><div className="period-divider"/><div><span>VAT Basis</span><strong>{vatLabel(form.vatBasis,form.vatRate)}</strong></div></div>
  <div className="metrics-section"><div className="metrics-heading"><div><span className="entry-step">VALUES</span><h3>Financial Metrics</h3></div>{selectedStream&&<span className="selected-stream-pill">{selectedStream.name}</span>}</div>{!form.revenueStreamId?<div className="metric-placeholder"><strong>Select a revenue stream</strong></div>:<div className="metric-input-grid">{streamMetrics.map(m=><label className="metric-entry-card" key={m.id}><span>{metricLabel(m)}</span><div className="money-input"><span>{metricUnit(m)}</span><input type="number" min="0" step="0.01" value={metricValues[m.id]??""} onChange={e=>setMetricValues(c=>({...c,[m.id]:e.target.value}))}/></div></label>)}</div>}</div></section>
  <aside className="data-entry-review-card"><div className="review-header"><span className="entry-step">REVIEW</span><h3>Record Summary</h3></div><div className="review-list"><div><span>School</span><strong>{selectedSchool?.name||"—"}</strong></div><div><span>Revenue Stream</span><strong>{selectedStream?.name||"—"}</strong></div>{isLeasing&&<div><span>Programme</span><strong>{selectedProgramme?.name||"—"}</strong></div>}<div><span>Academic Year</span><strong>{academicYear||"—"}</strong></div><div><span>Term</span><strong>{term||"—"}</strong></div><div><span>Scenario</span><strong>{form.scenario}</strong></div><div><span>VAT</span><strong>{vatLabel(form.vatBasis,form.vatRate)}</strong></div></div>{error&&<div className="entry-message error">{error}</div>}{success&&<div className="entry-message success">{success}</div>}<div className="entry-actions"><button type="button" className="entry-reset-button" onClick={reset}>Reset</button><button type="submit" className="entry-save-button" disabled={saving||!canEdit}>{saving?"Saving…":"Save Records"}</button></div></aside></form>
  :<section className="manage-records-card"><div className="manage-records-header"><div><span className="entry-step">RECORD LIBRARY</span><h3>Manage Financial Records</h3></div><div className="record-count-badge">{displayCount} records</div></div><div className="record-filter-grid">
   <label className="entry-field search-field"><span>Search</span><input type="search" placeholder="School, programme, stream, metric…" value={recordFilters.search} onChange={e=>filter("search",e.target.value)}/></label><label className="entry-field"><span>Revenue Stream</span><select value={recordFilters.revenueStreamId} onChange={e=>filter("revenueStreamId",e.target.value)}><option value="">All Streams</option>{options.revenueStreams.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label className="entry-field"><span>Academic Year</span><select value={recordFilters.academicYear} onChange={e=>filter("academicYear",e.target.value)}><option value="">All Years</option>{availableAcademicYears.map(y=><option key={y}>{y}</option>)}</select></label><label className="entry-field"><span>Month</span><select value={recordFilters.month} onChange={e=>filter("month",e.target.value)} disabled={!recordFilters.academicYear}><option value="">All Months</option>{monthOptions.map(m=><option key={m.value} value={m.value}>{m.label}</option>)}</select></label><label className="entry-field"><span>School</span><select value={recordFilters.schoolId} onChange={e=>filter("schoolId",e.target.value)}><option value="">All Schools</option>{options.schools.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label className="entry-field"><span>Metric</span><select value={recordFilters.metricCode} onChange={e=>filter("metricCode",e.target.value)}><option value="">All Metrics</option>{managementMetrics.map(m=><option key={metricKey(m)} value={metricKey(m)}>{metricLabel(m)}</option>)}</select></label><label className="entry-field"><span>Scenario</span><select value={recordFilters.scenario} onChange={e=>filter("scenario",e.target.value)}><option value="">All Scenarios</option>{SCENARIOS.map(s=><option key={s}>{s}</option>)}</select></label>{showManagementProgramme&&<><label className="entry-field"><span>Category</span><select value={recordFilters.category} onChange={e=>filter("category",e.target.value)}><option value="">All Categories</option>{leasingCategories.map(c=><option key={c}>{c}</option>)}</select></label><label className="entry-field"><span>Programme</span><select value={recordFilters.programmeId} onChange={e=>filter("programmeId",e.target.value)}><option value="">All Programmes</option>{leasingProgrammes.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label></>}<label className="archive-toggle"><input type="checkbox" checked={recordFilters.includeDeleted} onChange={e=>filter("includeDeleted",e.target.checked)}/><span>Show archived</span></label>
  </div>{recordsError&&<div className="entry-message error manage-message">{recordsError}</div>}{recordsLoading?<div className="records-loading">Loading records…</div>:displayCount===0?<div className="records-empty"><strong>No records found</strong></div>:<><div className="records-table-wrap"><table className="records-table"><thead><tr><th>Period</th><th>School</th>{showManagementProgramme&&<th>Programme</th>}<th>Revenue Stream</th><th>Metric</th><th>Scenario</th><th>Amount</th><th>VAT Basis</th><th>Status</th><th/></tr></thead><tbody>{displayRecords.map(r=><tr key={r.id} className={r.is_deleted?"archived-row":""}><td><strong>{formatRecordMonth(r.month)}</strong><span>{r.academic_year}</span></td><td><strong>{r.school?.name||"—"}</strong><span>{r.school?.code||""}</span></td>{showManagementProgramme&&<td><strong>{r.programme?.name||"—"}</strong>{r.programme?.provider_name&&<span>{r.programme.provider_name}</span>}</td>}<td>{r.revenue_stream?.name||"—"}</td><td>{metricLabel(r.metric)}</td><td><span className={`scenario-pill ${String(r.scenario||"").toLowerCase()}`}>{r.scenario||"—"}</span></td><td className="record-amount">{formatMetricValue(r.amount,r.metric)}</td><td><span className={`vat-basis-pill ${r.vat_basis?"classified":"unclassified"}`}>{vatLabel(r.vat_basis,r.vat_rate)}</span></td><td><span className={`record-status ${r.is_deleted?"archived":"active"}`}>{r.is_deleted?"Archived":"Active"}</span></td><td className="record-actions-cell">{r.is_deleted?canRestore&&<button className="record-action restore" onClick={()=>restore(r)}>Restore</button>:<div className="record-actions"><button className="record-action" onClick={()=>openEdit(r)}>Edit</button><button className="record-action danger" onClick={()=>setDeleteRecord(r)}>Archive</button></div>}</td></tr>)}</tbody></table></div><div className="records-pagination"><div className="pagination-summary">Showing <strong>{pageStart}–{pageEnd}</strong> of <strong>{displayCount}</strong> records</div><div className="pagination-controls"><button className="pagination-arrow" onClick={()=>setCurrentPage(p=>Math.max(1,p-1))} disabled={currentPage===1}>‹</button>{paginationItems.map(i=>typeof i==="number"?<button key={i} className={`pagination-page ${currentPage===i?"active":""}`} onClick={()=>setCurrentPage(i)}>{i}</button>:<span key={i}>…</span>)}<button className="pagination-arrow" onClick={()=>setCurrentPage(p=>Math.min(totalPages,p+1))} disabled={currentPage===totalPages}>›</button></div></div></>}</section>}
  {editingRecord&&<div className="record-modal-backdrop"><div className="record-modal edit-record-modal"><div className="record-modal-header"><div><span className="entry-step">EDIT RECORD</span><h3>{metricLabel(editingRecord.metric)}</h3><p>Change the amount or classify its VAT basis.</p></div><button className="modal-close" onClick={()=>setEditingRecord(null)}>×</button></div><div className="edit-record-context"><div><span>School</span><strong>{editingRecord.school?.name}</strong></div>{editingRecord.revenue_stream?.code==="leasing"&&<div><span>Programme</span><strong>{editingRecord.programme?.name||"—"}</strong></div>}<div><span>Revenue Stream</span><strong>{editingRecord.revenue_stream?.name}</strong></div><div><span>Period</span><strong>{formatRecordMonth(editingRecord.month)}</strong></div></div><label className="entry-field edit-amount-field"><span>Amount</span><div className="edit-money-input"><span className="edit-currency">{metricUnit(editingRecord.metric)}</span><input type="text" inputMode="decimal" value={editAmount} onChange={e=>setEditAmount(e.target.value)} autoFocus/></div></label><div className="vat-edit-grid"><label className="entry-field"><span>Entered Amount VAT Basis</span><select value={editVatBasis} onChange={e=>{setEditVatBasis(e.target.value);if(e.target.value===VAT_BASES.NO_VAT)setEditVatRate("0");}}><option value="">Select VAT basis</option>{VAT_OPTIONS.map(o=><option key={o.value} value={o.value}>{o.label}</option>)}</select></label><label className="entry-field"><span>VAT Rate (%)</span><input type="number" min="0" max="100" step="0.01" value={editVatRate} disabled={editVatBasis===VAT_BASES.NO_VAT} onChange={e=>setEditVatRate(e.target.value)}/></label></div>{!editingRecord.vat_basis&&<div className="vat-history-note">This historical record has not yet been classified. Choose the basis of the amount originally entered; the amount itself will not be converted.</div>}<div className="record-modal-actions"><button className="entry-reset-button" onClick={()=>setEditingRecord(null)}>Cancel</button><button className="entry-save-button" onClick={saveEdit} disabled={recordActionLoading||editAmount===""||!editVatBasis}>{recordActionLoading?"Saving…":"Save Changes"}</button></div></div></div>}
  {deleteRecord&&<div className="record-modal-backdrop"><div className="record-modal delete-modal"><div className="delete-icon">!</div><h3>Archive financial record?</h3><p>This record will disappear from normal dashboards but remain in the audit history and can be restored later.</p><div className="delete-record-summary"><strong>{deleteRecord.school?.name}</strong><span>{deleteRecord.programme?.name?`${deleteRecord.programme.name} · `:""}{deleteRecord.revenue_stream?.name} · {metricLabel(deleteRecord.metric)}</span><span>{formatRecordMonth(deleteRecord.month)} · {deleteRecord.scenario}</span><b>{formatMetricValue(deleteRecord.amount,deleteRecord.metric)}</b></div><div className="record-modal-actions"><button className="entry-reset-button" onClick={()=>setDeleteRecord(null)}>Cancel</button><button className="archive-confirm-button" onClick={archive} disabled={recordActionLoading}>{recordActionLoading?"Archiving…":"Archive Record"}</button></div></div></div>}
 </section>;
}
