import { useState } from "react";
import { useAuth } from "../../auth/AuthProvider";
import { fetchDataEntryOptions } from "../../lib/financialData";
import { checkFinancialImportConflicts,downloadFinancialImportTemplate,importFinancialRows,readFinancialImportFile,validateFinancialImportRows } from "../../lib/financialBulkImport";
import "./FinancialBulkImport.css";

const money=v=>new Intl.NumberFormat("en-AE",{style:"currency",currency:"AED",maximumFractionDigits:2}).format(Number(v||0));
export default function FinancialBulkImport(){
 const {role}=useAuth(),canEdit=role==="admin"||role==="editor";
 const [file,setFile]=useState(null),[rows,setRows]=useState([]),[loading,setLoading]=useState(false),[importing,setImporting]=useState(false),[overwrite,setOverwrite]=useState(false),[error,setError]=useState(""),[result,setResult]=useState(null);
 const ready=rows.filter(r=>r.status==="ready").length,existing=rows.filter(r=>r.status==="existing").length,invalid=rows.filter(r=>r.status==="invalid").length;
 async function choose(e){const selected=e.target.files?.[0];setFile(selected||null);setRows([]);setResult(null);setOverwrite(false);setError("");if(!selected)return;try{setLoading(true);const [raw,options]=await Promise.all([readFinancialImportFile(selected),fetchDataEntryOptions()]);setRows(await checkFinancialImportConflicts(validateFinancialImportRows(raw,options)))}catch(err){setError(err?.message||"We could not read this file. Check the template and try again.")}finally{setLoading(false)}}
 async function run(){if(!canEdit)return setError("Your account does not have permission to import financial records.");if(invalid)return setError("Resolve the invalid rows before importing.");try{setImporting(true);setError("");const summary=await importFinancialRows(rows,{overwriteExisting:overwrite});setResult(summary);setRows([]);setFile(null);setOverwrite(false)}catch(err){setError(err?.message||"The import could not be completed. No further rows will be processed.")}finally{setImporting(false)}}
 return <section className="bulk-import-card">
  <div className="bulk-import-head"><div><span>BULK IMPORT</span><h3>Import Monthly Financial Records</h3><p>Use the standard Excel template, review every row before posting, and keep existing records protected by default.</p></div><button type="button" className="bulk-template" onClick={downloadFinancialImportTemplate}>↓ Download Template</button></div>
  <div className="bulk-upload"><div><strong>{file?.name||"Choose completed Excel template"}</strong><span>{file?"The file will be validated before anything is saved.":"Accepted format: .xlsx"}</span></div><label><input type="file" accept=".xlsx" onChange={choose}/>{loading?"Checking…":"Choose File"}</label></div>
  {error&&<div className="bulk-message error">{error}</div>}{result&&<div className="bulk-message success">Import complete — {result.inserted} added, {result.updated} updated and {result.skipped} protected.</div>}
  {!!rows.length&&<><div className="bulk-summary"><div><span>Ready to add</span><strong>{ready}</strong></div><div><span>Existing records</span><strong>{existing}</strong></div><div><span>Needs attention</span><strong>{invalid}</strong></div><div><span>Total rows</span><strong>{rows.length}</strong></div></div>
   {existing>0&&<label className="bulk-overwrite"><input type="checkbox" checked={overwrite} onChange={e=>setOverwrite(e.target.checked)}/><span><strong>Allow existing records to be overwritten</strong><small>Off by default. If left off, existing values remain unchanged and only empty records are added.</small></span></label>}
   <div className="bulk-preview"><div className="bulk-preview-head"><strong>Validation Preview</strong><span>Nothing has been saved yet.</span></div><div className="bulk-table-wrap"><table><thead><tr><th>Status</th><th>School</th><th>Revenue Stream</th><th>Programme</th><th>Month</th><th>Scenario</th><th>Metric</th><th>Amount</th></tr></thead><tbody>{rows.slice(0,100).map(r=><tr key={r.rowNumber} className={`bulk-row ${r.status}`}><td><span className={`bulk-status ${r.status}`}>{r.status==="ready"?"Ready":r.status==="existing"?"Existing":"Check row"}</span>{r.errors.length>0&&<small>{r.errors.join(" · ")}</small>}</td><td>{r.school?.code||"—"}</td><td>{r.stream?.name||"—"}</td><td>{r.programme?.name||"—"}</td><td>{r.month||"—"}</td><td>{r.scenario}</td><td>{r.metric?.name||"—"}</td><td>{Number.isFinite(r.amount)?money(r.amount):"—"}</td></tr>)}</tbody></table></div>{rows.length>100&&<p className="bulk-more">Showing the first 100 of {rows.length} rows.</p>}</div>
   <div className="bulk-actions"><p>{invalid?`${invalid} row${invalid===1?"":"s"} must be corrected before import.`:existing&&!overwrite?`${existing} existing row${existing===1?"":"s"} will be safely skipped.`:"Ready to import."}</p><button type="button" onClick={run} disabled={importing||invalid>0||(!ready&&!overwrite)}>{importing?"Importing…":`Import ${overwrite?ready+existing:ready} Record${(overwrite?ready+existing:ready)===1?"":"s"}`}</button></div>
  </>}
 </section>
}
