import { useState } from "react";
import { useAuth } from "../../auth/AuthProvider";
import { fetchDataEntryOptions } from "../../lib/financialData";
import { checkFinancialImportConflicts,downloadFinancialImportTemplate,importFinancialRows,readFinancialImportFile,validateFinancialImportRows } from "../../lib/financialBulkImport";
import "./FinancialBulkImport.css";

const money=v=>new Intl.NumberFormat("en-AE",{style:"currency",currency:"AED",maximumFractionDigits:2}).format(Number(v||0));
export default function FinancialBulkImport({onReviewRecords}){
 const {role}=useAuth(),canEdit=role==="admin"||role==="editor";
 const [file,setFile]=useState(null),[rows,setRows]=useState([]),[loading,setLoading]=useState(false),[importing,setImporting]=useState(false),[overwrite,setOverwrite]=useState(false),[error,setError]=useState(""),[result,setResult]=useState(null);
 const ready=rows.filter(r=>r.status==="ready").length,existing=rows.filter(r=>r.status==="existing").length,invalid=rows.filter(r=>r.status==="invalid").length,willPost=overwrite?ready+existing:ready;
 async function choose(e){const selected=e.target.files?.[0];setFile(selected||null);setRows([]);setResult(null);setOverwrite(false);setError("");if(!selected)return;try{setLoading(true);const [raw,options]=await Promise.all([readFinancialImportFile(selected),fetchDataEntryOptions()]);setRows(await checkFinancialImportConflicts(validateFinancialImportRows(raw,options)))}catch(err){setError(err?.message||"We could not read this file. Check the template and try again.")}finally{setLoading(false)}}
 async function run(){if(!canEdit)return setError("Your account does not have permission to import financial records.");if(invalid)return setError("Resolve the rows marked Need attention before importing.");if(!willPost)return setError("There are no new records to import.");try{setImporting(true);setError("");const summary=await importFinancialRows(rows,{overwriteExisting:overwrite});setResult(summary);setRows([]);setFile(null);setOverwrite(false)}catch(err){setError(err?.message||"The import could not be completed. No records were changed.")}finally{setImporting(false)}}
 return <section className="bulk-import-card">
  <div className="bulk-import-head"><div><span>BULK IMPORT</span><h3>Import Monthly Financial Records</h3><p>Use the standard Excel template, review every row before posting, and keep existing records protected by default.</p></div><button type="button" className="bulk-template" onClick={downloadFinancialImportTemplate}>↓ Download Template</button></div>
  <div className="bulk-upload"><div><strong>{file?.name||"Choose completed Excel template"}</strong><span>{file?"The file will be validated before anything is saved.":"Accepted format: .xlsx"}</span></div><label><input type="file" accept=".xlsx" onChange={choose}/>{loading?"Checking…":"Choose File"}</label></div>
  {error&&<div className="bulk-message error">{error}</div>}
  {result&&<div className="bulk-complete"><div className="bulk-complete-mark">✓</div><div className="bulk-complete-copy"><span>IMPORT COMPLETE</span><h4>Financial records posted successfully</h4><p>The import was processed as one controlled database transaction.</p><div className="bulk-complete-stats"><strong>{result.inserted}<small>Added</small></strong><strong>{result.updated}<small>Updated</small></strong><strong>{result.skipped}<small>Protected</small></strong></div></div>{onReviewRecords&&<button type="button" onClick={onReviewRecords}>Review in Find Records →</button>}</div>}
  {!!rows.length&&<><div className="bulk-summary"><div><span>Ready to add</span><strong>{ready}</strong></div><div><span>Existing records</span><strong>{existing}</strong></div><div><span>Needs attention</span><strong>{invalid}</strong></div><div><span>Total rows</span><strong>{rows.length}</strong></div></div>
   {existing>0&&<label className={`bulk-overwrite ${overwrite?"enabled":""}`}><input type="checkbox" checked={overwrite} onChange={e=>setOverwrite(e.target.checked)}/><span><strong>{overwrite?`Overwrite enabled for ${existing} existing record${existing===1?"":"s"}`:"Protect existing records"}</strong><small>{overwrite?"The matching values shown as Existing will be replaced when you import. New rows will still be added normally.":"Recommended. Existing values will remain unchanged and only new records will be added. Tick this box only when you deliberately want the Excel values to replace existing records."}</small></span></label>}
   {overwrite&&existing>0&&<div className="bulk-overwrite-warning"><strong>Existing data will be changed.</strong><span>Review the rows marked Existing before continuing. This import will replace their current amounts with the values in this file.</span></div>}
   <div className="bulk-preview"><div className="bulk-preview-head"><strong>Validation Preview</strong><span>Nothing has been saved yet.</span></div><div className="bulk-table-wrap"><table><thead><tr><th>Status</th><th>School</th><th>Revenue Stream</th><th>Programme</th><th>Month</th><th>Scenario</th><th>Metric</th><th>Amount</th></tr></thead><tbody>{rows.slice(0,100).map(r=><tr key={r.rowNumber} className={`bulk-row ${r.status}`}><td><span className={`bulk-status ${r.status}`}>{r.status==="ready"?"Ready":r.status==="existing"?"Existing":"Check row"}</span>{r.errors.length>0&&<small>{r.errors.join(" · ")}</small>}</td><td>{r.school?.code||"—"}</td><td>{r.stream?.name||"—"}</td><td>{r.programme?.name||"—"}</td><td>{r.month||"—"}</td><td>{r.scenario}</td><td>{r.metric?.name||"—"}</td><td>{Number.isFinite(r.amount)?money(r.amount):"—"}</td></tr>)}</tbody></table></div>{rows.length>100&&<p className="bulk-more">Showing the first 100 of {rows.length} rows.</p>}</div>
   <div className="bulk-actions"><div><strong>{invalid?"Import not ready":overwrite&&existing?"Overwrite authorised":existing?"Existing data protected":"Ready to import"}</strong><p>{invalid?`${invalid} row${invalid===1?"":"s"} must be corrected in the Excel file and uploaded again.`:overwrite&&existing?`${ready} new and ${existing} existing record${ready+existing===1?"":"s"} will be posted.`:existing?`${ready} new record${ready===1?"":"s"} will be added; ${existing} existing record${existing===1?"":"s"} will be left unchanged.`:`${ready} new record${ready===1?"":"s"} will be added.`}</p></div><button type="button" onClick={run} disabled={importing||invalid>0||!willPost}>{importing?"Posting Import…":`Import ${willPost} Record${willPost===1?"":"s"}`}</button></div>
  </>}
 </section>
}
