import { useEffect, useMemo, useState } from "react";
import { Link } from "react-router-dom";
import { fetchSupplierContracts, fetchSupplierDirectoryFilters } from "../../lib/supplierDirectoryData";
import "./SupplierDirectoryPage.css";

const DAY=24*60*60*1000;
function formatDate(value){if(!value)return"Not recorded";return new Intl.DateTimeFormat("en-GB",{day:"2-digit",month:"short",year:"numeric"}).format(new Date(`${value}T00:00:00`))}
function getStatus(item){const today=new Date();today.setHours(0,0,0,0);if(!item.isActive)return"Inactive";if(item.startDate){const start=new Date(`${item.startDate}T00:00:00`);if(start>today)return"Future Contract"}if(item.expiryDate){const expiry=new Date(`${item.expiryDate}T00:00:00`);if(expiry<today)return"Expired";const days=Math.ceil((expiry-today)/DAY);if(days<=90)return`Expiring Soon · ${days}d`}if(!item.expiryDate)return"No Expiry Recorded";return item.status&&item.status!=="Not Recorded"?item.status:"Active"}
function statusBucket(item){const status=getStatus(item);if(status.startsWith("Expiring Soon"))return"expiring";if(status==="Expired"||status==="Inactive")return"history";if(status==="No Expiry Recorded")return"attention";return"current"}
function statusClass(status){const value=status.toLowerCase();if(value.includes("expiring"))return"warning";if(value.includes("expired")||value.includes("inactive"))return"danger";if(value.includes("future"))return"info";if(value.includes("no expiry")||value.includes("not recorded"))return"neutral";if(value.includes("active"))return"success";return"neutral"}
function commercialTerms(item){const parts=[];if(item.commissionRate!=null)parts.push(`${(item.commissionRate*100).toFixed(item.commissionRate*100%1?1:0)}% commission`);if(item.rentalFeesDescription)parts.push(item.rentalFeesDescription);else if(item.rentalFeesAmount!=null)parts.push(`AED ${item.rentalFeesAmount.toLocaleString("en-AE")} rental`);return parts.join(" · ")||"Not recorded"}
function primaryContact(item){return item.contacts.find(contact=>contact.isPrimary)||item.contacts[0]||null}
function missingInfoCount(item){let count=0;if(!item.expiryDate)count++;if(!item.contacts?.length&&!item.contactPerson&&!item.email&&!item.phone)count++;if(item.commissionRate==null&&!item.rentalFeesDescription&&item.rentalFeesAmount==null)count++;return count}

export default function SupplierDirectoryPage(){
 const[contracts,setContracts]=useState([]),[streams,setStreams]=useState([]),[schools,setSchools]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const[stream,setStream]=useState(""),[school,setSchool]=useState(""),[status,setStatus]=useState("current"),[search,setSearch]=useState(""),[selected,setSelected]=useState(null),[collapsed,setCollapsed]=useState({});
 useEffect(()=>{let active=true;(async()=>{try{setLoading(true);const[rows,filters]=await Promise.all([fetchSupplierContracts(),fetchSupplierDirectoryFilters()]);if(!active)return;setContracts(rows);setStreams(filters.streams);setSchools(filters.schools)}catch(err){console.error(err);if(active)setError("Unable to load the Supplier & Contract Register. Run the latest supplier directory database migration first.")}finally{if(active)setLoading(false)}})();return()=>{active=false}},[]);
 const filtered=useMemo(()=>contracts.filter(item=>{const bucket=statusBucket(item);if(stream&&item.revenueStreamCode!==stream)return false;if(school&&!item.schools.some(s=>s.code===school))return false;if(status==="current"&&bucket==="history")return false;if(status==="history"&&bucket!=="history")return false;if(status==="attention"&&bucket!=="attention"&&bucket!=="expiring")return false;if(search){const contactText=item.contacts.flatMap(c=>[c.name,c.role,c.email,c.phone]);const haystack=[item.supplierName,item.legalName,item.contactPerson,item.email,item.phone,item.companyNumber,item.vatTrn,item.revenueStreamName,item.status,item.noticePeriod,item.invoiceFrequency,item.revenueCollection,...contactText,...item.schools.map(s=>s.name),...item.schools.map(s=>s.code)].join(" ").toLowerCase();if(!haystack.includes(search.toLowerCase()))return false}return true}),[contracts,stream,school,status,search]);
 const summary=useMemo(()=>{const current=contracts.filter(item=>statusBucket(item)!=="history");return{contracts:current.length,suppliers:new Set(current.map(item=>item.providerId)).size,expiring:current.filter(item=>statusBucket(item)==="expiring").length,attention:current.filter(item=>statusBucket(item)==="attention"||missingInfoCount(item)>1).length}},[contracts]);
 const grouped=useMemo(()=>{const map=new Map();filtered.forEach(item=>{const key=item.revenueStreamName||"Not assigned";if(!map.has(key))map.set(key,[]);map.get(key).push(item)});return[...map.entries()].sort((a,b)=>a[0].localeCompare(b[0]))},[filtered]);
 function clearFilters(){setStream("");setSchool("");setStatus("current");setSearch("")}
 function applySummary(type){setStream("");setSchool("");setSearch("");if(type==="contracts"||type==="suppliers")setStatus("current");if(type==="expiring")setStatus("attention");if(type==="attention")setStatus("attention")}
 function toggleGroup(name){setCollapsed(current=>({...current,[name]:!current[name]}))}
 if(loading)return <section className="supplier-directory"><div className="supplier-empty">Loading Supplier & Contract Register…</div></section>;
 if(error)return <section className="supplier-directory"><div className="supplier-empty">{error}</div></section>;
 return <section className="supplier-directory">
  <div className="supplier-summary">
   <button type="button" onClick={()=>applySummary("contracts")}><span>Active contracts</span><strong>{summary.contracts}</strong><small>Current relationships</small></button>
   <button type="button" onClick={()=>applySummary("suppliers")}><span>Current suppliers</span><strong>{summary.suppliers}</strong><small>Across active contracts</small></button>
   <button type="button" onClick={()=>applySummary("expiring")}><span>Expiring soon</span><strong>{summary.expiring}</strong><small>Within 90 days</small></button>
   <button type="button" onClick={()=>applySummary("attention")}><span>Needs attention</span><strong>{summary.attention}</strong><small>Missing or time-sensitive data</small></button>
  </div>
  <div className="supplier-toolbar"><label><span>Revenue Stream</span><select value={stream} onChange={e=>setStream(e.target.value)}><option value="">All Revenue Streams</option>{streams.map(item=><option key={item.id} value={item.code}>{item.name}</option>)}</select></label><label><span>School</span><select value={school} onChange={e=>setSchool(e.target.value)}><option value="">All Schools</option>{schools.map(item=><option key={item.id} value={item.code}>{item.name}</option>)}</select></label><label><span>Contracts</span><select value={status} onChange={e=>setStatus(e.target.value)}><option value="current">Current</option><option value="history">History</option><option value="attention">Needs Attention</option><option value="all">Current + History</option></select></label><label className="supplier-search"><span>Search</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Supplier, school, contact, TRN…"/></label><button type="button" className="supplier-clear" onClick={clearFilters}>Clear</button></div>
  <div className="supplier-register">{grouped.length===0?<div className="supplier-empty">No contracts match the selected filters.</div>:grouped.map(([streamName,items])=>{const isCollapsed=Boolean(collapsed[streamName]);return <section className="supplier-stream-group" key={streamName}><button type="button" className="supplier-stream-heading" onClick={()=>toggleGroup(streamName)}><div><span>Revenue Stream</span><h2>{streamName}</h2></div><div className="supplier-stream-heading-right"><b>{items.length} {items.length===1?"contract":"contracts"}</b><i>{isCollapsed?"›":"⌄"}</i></div></button>{!isCollapsed&&<div className="supplier-table-wrap"><table><thead><tr><th>Supplier</th><th>Schools</th><th>Contract Period</th><th>Status</th><th>Commercial Terms</th><th>Contact</th></tr></thead><tbody>{items.map(item=>{const itemStatus=getStatus(item),contact=primaryContact(item);return <tr key={item.contractId} onClick={()=>setSelected(item)}><td><strong>{item.supplierName}</strong>{item.legalName&&item.legalName!==item.supplierName&&<small>{item.legalName}</small>}</td><td><div className="school-chips">{item.schools.length?item.schools.map(s=><span key={s.id}>{s.code}</span>):<em>Not recorded</em>}</div></td><td>{formatDate(item.startDate)} <span className="period-arrow">→</span> {formatDate(item.expiryDate)}</td><td><span className={`contract-status ${statusClass(itemStatus)}`}>{itemStatus}</span></td><td>{commercialTerms(item)}</td><td><strong className="contact-name">{contact?.name||item.contactPerson||"Not recorded"}</strong>{(contact?.email||item.email)&&<small>{contact?.email||item.email}</small>}</td></tr>})}</tbody></table></div>}</section>})}</div>
  {selected&&<div className="supplier-detail-backdrop" onClick={()=>setSelected(null)}><aside className="supplier-detail" onClick={e=>e.stopPropagation()}><button className="supplier-detail-close" onClick={()=>setSelected(null)}>×</button><span className="detail-kicker">{selected.revenueStreamName}</span><h2>{selected.supplierName}</h2>{selected.legalName&&selected.legalName!==selected.supplierName&&<p>{selected.legalName}</p>}<div className="detail-status"><span className={`contract-status ${statusClass(getStatus(selected))}`}>{getStatus(selected)}</span></div><div className="supplier-detail-actions"><Link to="/supplier-records">Edit in Records →</Link></div><section><h3>Contract</h3><dl><div><dt>Schools</dt><dd>{selected.schools.map(s=>s.name).join(", ")||"Not recorded"}</dd></div><div><dt>Start date</dt><dd>{formatDate(selected.startDate)}</dd></div><div><dt>Expiry date</dt><dd>{formatDate(selected.expiryDate)}</dd></div><div><dt>Notice period</dt><dd>{selected.noticePeriod||"Not recorded"}</dd></div><div><dt>Commission</dt><dd>{selected.commissionRate==null?"Not recorded":`${(selected.commissionRate*100).toFixed(selected.commissionRate*100%1?1:0)}%`}</dd></div><div><dt>Other commercial terms</dt><dd>{selected.rentalFeesDescription||(selected.rentalFeesAmount!=null?`AED ${selected.rentalFeesAmount.toLocaleString("en-AE")}`:"Not recorded")}</dd></div><div><dt>Revenue collection</dt><dd>{selected.revenueCollection||"Not recorded"}</dd></div><div><dt>Invoice frequency</dt><dd>{selected.invoiceFrequency||"Not recorded"}</dd></div></dl></section><section><h3>Company details</h3><dl><div><dt>Legal name</dt><dd>{selected.legalName||selected.supplierName||"Not recorded"}</dd></div><div><dt>Company registration no.</dt><dd>{selected.companyNumber||"Not recorded"}</dd></div><div><dt>VAT / TRN</dt><dd>{selected.vatTrn||"Not recorded"}</dd></div><div><dt>Address</dt><dd>{selected.address||"Not recorded"}</dd></div><div><dt>General phone</dt><dd>{selected.phone||"Not recorded"}</dd></div><div><dt>General email</dt><dd>{selected.email||"Not recorded"}</dd></div></dl></section><section><h3>Contacts</h3>{selected.contacts.length?<dl>{selected.contacts.map(contact=><div key={contact.id}><dt>{contact.role||"Contact"}{contact.isPrimary?" · Primary":""}</dt><dd><strong>{contact.name}</strong>{contact.email&&<><br/>{contact.email}</>}{contact.phone&&<><br/>{contact.phone}</>}</dd></div>)}</dl>:<dl><div><dt>Primary contact</dt><dd>{selected.contactPerson||"Not recorded"}{selected.email&&<><br/>{selected.email}</>}{selected.phone&&<><br/>{selected.phone}</>}</dd></div></dl>}</section></aside></div>}
 </section>;
}
