import { useEffect, useMemo, useState } from "react";
import { fetchSupplierContracts, fetchSupplierDirectoryFilters } from "../../lib/supplierDirectoryData";
import "./SupplierDirectoryPage.css";

const DAY=24*60*60*1000;
function formatDate(value){if(!value)return"—";return new Intl.DateTimeFormat("en-GB",{day:"2-digit",month:"short",year:"numeric"}).format(new Date(`${value}T00:00:00`))}
function getStatus(item){const today=new Date();today.setHours(0,0,0,0);if(!item.isActive)return"Inactive";if(item.expiryDate){const expiry=new Date(`${item.expiryDate}T00:00:00`);if(expiry<today)return"Expired";if((expiry-today)/DAY<=90)return"Expiring Soon"}return item.status&&item.status!=="Not Recorded"?item.status:"Active"}
function statusClass(status){const value=status.toLowerCase();if(value.includes("expiring"))return"warning";if(value.includes("expired")||value.includes("inactive"))return"danger";if(value.includes("active"))return"success";return"neutral"}
function commercialTerms(item){const parts=[];if(item.commissionRate!=null)parts.push(`${(item.commissionRate*100).toFixed(item.commissionRate*100%1?1:0)}% commission`);if(item.rentalFeesDescription)parts.push(item.rentalFeesDescription);else if(item.rentalFeesAmount!=null)parts.push(`AED ${item.rentalFeesAmount.toLocaleString("en-AE")} rental`);return parts.join(" · ")||"—"}
function primaryContact(item){return item.contacts.find(contact=>contact.isPrimary)||item.contacts[0]||null}

export default function SupplierDirectoryPage(){
 const[contracts,setContracts]=useState([]),[streams,setStreams]=useState([]),[schools,setSchools]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState("");
 const[stream,setStream]=useState(""),[school,setSchool]=useState(""),[status,setStatus]=useState("current"),[search,setSearch]=useState(""),[selected,setSelected]=useState(null);
 useEffect(()=>{let active=true;(async()=>{try{setLoading(true);const[rows,filters]=await Promise.all([fetchSupplierContracts(),fetchSupplierDirectoryFilters()]);if(!active)return;setContracts(rows);setStreams(filters.streams);setSchools(filters.schools)}catch(err){console.error(err);if(active)setError("Unable to load the Supplier & Contract Register. Run the latest supplier directory database migration first.")}finally{if(active)setLoading(false)}})();return()=>{active=false}},[]);
 const filtered=useMemo(()=>contracts.filter(item=>{const calculated=getStatus(item);if(stream&&item.revenueStreamCode!==stream)return false;if(school&&!item.schools.some(s=>s.code===school))return false;if(status==="current"&&(calculated==="Expired"||calculated==="Inactive"))return false;if(status==="history"&&calculated!=="Expired"&&calculated!=="Inactive")return false;if(search){const contactText=item.contacts.flatMap(c=>[c.name,c.role,c.email,c.phone]);const haystack=[item.supplierName,item.legalName,item.contactPerson,item.email,item.companyNumber,item.vatTrn,item.revenueStreamName,...contactText,...item.schools.map(s=>s.name),...item.schools.map(s=>s.code)].join(" ").toLowerCase();if(!haystack.includes(search.toLowerCase()))return false}return true}),[contracts,stream,school,status,search]);
 const summary=useMemo(()=>{const current=contracts.filter(item=>!["Expired","Inactive"].includes(getStatus(item)));return{contracts:current.length,suppliers:new Set(current.map(item=>item.providerId)).size,expiring:current.filter(item=>getStatus(item)==="Expiring Soon").length,streams:new Set(current.map(item=>item.revenueStreamCode).filter(Boolean)).size}},[contracts]);
 const grouped=useMemo(()=>{const map=new Map();filtered.forEach(item=>{const key=item.revenueStreamName||"Not assigned";if(!map.has(key))map.set(key,[]);map.get(key).push(item)});return[...map.entries()]},[filtered]);
 if(loading)return <section className="supplier-directory"><div className="supplier-empty">Loading Supplier & Contract Register…</div></section>;
 if(error)return <section className="supplier-directory"><div className="supplier-empty">{error}</div></section>;
 return <section className="supplier-directory">
  <div className="supplier-summary"><article><span>Active contracts</span><strong>{summary.contracts}</strong></article><article><span>Current suppliers</span><strong>{summary.suppliers}</strong></article><article><span>Expiring soon</span><strong>{summary.expiring}</strong></article><article><span>Revenue streams covered</span><strong>{summary.streams}</strong></article></div>
  <div className="supplier-toolbar"><label><span>Revenue Stream</span><select value={stream} onChange={e=>setStream(e.target.value)}><option value="">All Revenue Streams</option>{streams.map(item=><option key={item.id} value={item.code}>{item.name}</option>)}</select></label><label><span>School</span><select value={school} onChange={e=>setSchool(e.target.value)}><option value="">All Schools</option>{schools.map(item=><option key={item.id} value={item.code}>{item.name}</option>)}</select></label><label><span>Contracts</span><select value={status} onChange={e=>setStatus(e.target.value)}><option value="current">Current</option><option value="history">History</option><option value="all">Current + History</option></select></label><label className="supplier-search"><span>Search</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Supplier, contact or school"/></label></div>
  <div className="supplier-register">{grouped.length===0?<div className="supplier-empty">No contracts match the selected filters.</div>:grouped.map(([streamName,items])=><section className="supplier-stream-group" key={streamName}><div className="supplier-stream-heading"><div><span>Revenue Stream</span><h2>{streamName}</h2></div><b>{items.length} {items.length===1?"contract":"contracts"}</b></div><div className="supplier-table-wrap"><table><thead><tr><th>Supplier</th><th>Schools</th><th>Contract Period</th><th>Status</th><th>Commercial Terms</th><th>Contact</th></tr></thead><tbody>{items.map(item=>{const itemStatus=getStatus(item),contact=primaryContact(item);return <tr key={item.contractId} onClick={()=>setSelected(item)}><td><strong>{item.supplierName}</strong>{item.legalName&&item.legalName!==item.supplierName&&<small>{item.legalName}</small>}</td><td>{item.schools.length?item.schools.map(s=>s.code).join(", "):"—"}</td><td>{formatDate(item.startDate)} <span className="period-arrow">→</span> {formatDate(item.expiryDate)}</td><td><span className={`contract-status ${statusClass(itemStatus)}`}>{itemStatus}</span></td><td>{commercialTerms(item)}</td><td><strong className="contact-name">{contact?.name||item.contactPerson||"—"}</strong>{(contact?.email||item.email)&&<small>{contact?.email||item.email}</small>}</td></tr>})}</tbody></table></div></section>)}</div>
  {selected&&<div className="supplier-detail-backdrop" onClick={()=>setSelected(null)}><aside className="supplier-detail" onClick={e=>e.stopPropagation()}><button className="supplier-detail-close" onClick={()=>setSelected(null)}>×</button><span className="detail-kicker">{selected.revenueStreamName}</span><h2>{selected.supplierName}</h2>{selected.legalName&&selected.legalName!==selected.supplierName&&<p>{selected.legalName}</p>}<div className="detail-status"><span className={`contract-status ${statusClass(getStatus(selected))}`}>{getStatus(selected)}</span></div><section><h3>Contract</h3><dl><div><dt>Schools</dt><dd>{selected.schools.map(s=>s.name).join(", ")||"—"}</dd></div><div><dt>Start date</dt><dd>{formatDate(selected.startDate)}</dd></div><div><dt>Expiry date</dt><dd>{formatDate(selected.expiryDate)}</dd></div><div><dt>Notice period</dt><dd>{selected.noticePeriod||"—"}</dd></div><div><dt>Commission</dt><dd>{selected.commissionRate==null?"Not recorded yet":`${(selected.commissionRate*100).toFixed(selected.commissionRate*100%1?1:0)}%`}</dd></div><div><dt>Other commercial terms</dt><dd>{selected.rentalFeesDescription||(selected.rentalFeesAmount!=null?`AED ${selected.rentalFeesAmount.toLocaleString("en-AE")}`:"—")}</dd></div><div><dt>Revenue collection</dt><dd>{selected.revenueCollection||"—"}</dd></div><div><dt>Invoice frequency</dt><dd>{selected.invoiceFrequency||"—"}</dd></div></dl></section><section><h3>Company details</h3><dl><div><dt>Legal name</dt><dd>{selected.legalName||selected.supplierName||"—"}</dd></div><div><dt>Company registration no.</dt><dd>{selected.companyNumber||"—"}</dd></div><div><dt>VAT / TRN</dt><dd>{selected.vatTrn||"—"}</dd></div><div><dt>Address</dt><dd>{selected.address||"—"}</dd></div><div><dt>General phone</dt><dd>{selected.phone||"—"}</dd></div><div><dt>General email</dt><dd>{selected.email||"—"}</dd></div></dl></section><section><h3>Contacts</h3>{selected.contacts.length?<dl>{selected.contacts.map(contact=><div key={contact.id}><dt>{contact.role||"Contact"}{contact.isPrimary?" · Primary":""}</dt><dd><strong>{contact.name}</strong>{contact.email&&<><br/>{contact.email}</>}{contact.phone&&<><br/>{contact.phone}</>}</dd></div>)}</dl>:<dl><div><dt>Primary contact</dt><dd>{selected.contactPerson||"—"}{selected.email&&<><br/>{selected.email}</>}{selected.phone&&<><br/>{selected.phone}</>}</dd></div></dl>}</section></aside></div>}
 </section>;
}
